// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: darwin.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct DisruptionReason: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reasonID: UInt32 = 0

  public var reasonLocationID: String {
    get {_reasonLocationID ?? String()}
    set {_reasonLocationID = newValue}
  }
  /// Returns true if `reasonLocationID` has been explicitly set.
  public var hasReasonLocationID: Bool {self._reasonLocationID != nil}
  /// Clears the value of `reasonLocationID`. Subsequent reads from it will return its default value.
  public mutating func clearReasonLocationID() {self._reasonLocationID = nil}

  /// When true, the provided reason_id is 'near to' the provided reason_location_id. 
  /// When false, the reason_id is 'at' the reason_location_id.
  public var reasonIsNearLocation: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reasonLocationID: String? = nil
}

public struct Schedule: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uuid: String {
    get {_storage._uuid}
    set {_uniqueStorage()._uuid = newValue}
  }

  public var scheduleID: String {
    get {_storage._scheduleID}
    set {_uniqueStorage()._scheduleID = newValue}
  }

  public var uid: String {
    get {_storage._uid}
    set {_uniqueStorage()._uid = newValue}
  }

  public var headcode: String {
    get {_storage._headcode}
    set {_uniqueStorage()._headcode = newValue}
  }

  public var retailServiceID: String {
    get {_storage._retailServiceID ?? String()}
    set {_uniqueStorage()._retailServiceID = newValue}
  }
  /// Returns true if `retailServiceID` has been explicitly set.
  public var hasRetailServiceID: Bool {_storage._retailServiceID != nil}
  /// Clears the value of `retailServiceID`. Subsequent reads from it will return its default value.
  public mutating func clearRetailServiceID() {_uniqueStorage()._retailServiceID = nil}

  public var tocID: String {
    get {_storage._tocID}
    set {_uniqueStorage()._tocID = newValue}
  }

  public var service: ServiceType {
    get {_storage._service}
    set {_uniqueStorage()._service = newValue}
  }

  public var category: CategoryType {
    get {_storage._category}
    set {_uniqueStorage()._category = newValue}
  }

  public var isPassengerService: Bool {
    get {_storage._isPassengerService}
    set {_uniqueStorage()._isPassengerService = newValue}
  }

  public var isActive: Bool {
    get {_storage._isActive}
    set {_uniqueStorage()._isActive = newValue}
  }

  public var isCharter: Bool {
    get {_storage._isCharter}
    set {_uniqueStorage()._isCharter = newValue}
  }

  public var isCancelled: Bool {
    get {_storage._isCancelled}
    set {_uniqueStorage()._isCancelled = newValue}
  }

  public var cancellationReason: DisruptionReason {
    get {_storage._cancellationReason ?? DisruptionReason()}
    set {_uniqueStorage()._cancellationReason = newValue}
  }
  /// Returns true if `cancellationReason` has been explicitly set.
  public var hasCancellationReason: Bool {_storage._cancellationReason != nil}
  /// Clears the value of `cancellationReason`. Subsequent reads from it will return its default value.
  public mutating func clearCancellationReason() {_uniqueStorage()._cancellationReason = nil}

  public var divertedViaLocationID: String {
    get {_storage._divertedViaLocationID ?? String()}
    set {_uniqueStorage()._divertedViaLocationID = newValue}
  }
  /// Returns true if `divertedViaLocationID` has been explicitly set.
  public var hasDivertedViaLocationID: Bool {_storage._divertedViaLocationID != nil}
  /// Clears the value of `divertedViaLocationID`. Subsequent reads from it will return its default value.
  public mutating func clearDivertedViaLocationID() {_uniqueStorage()._divertedViaLocationID = nil}

  public var diversionReason: DisruptionReason {
    get {_storage._diversionReason ?? DisruptionReason()}
    set {_uniqueStorage()._diversionReason = newValue}
  }
  /// Returns true if `diversionReason` has been explicitly set.
  public var hasDiversionReason: Bool {_storage._diversionReason != nil}
  /// Clears the value of `diversionReason`. Subsequent reads from it will return its default value.
  public mutating func clearDiversionReason() {_uniqueStorage()._diversionReason = nil}

  public var forecast: Schedule.Forecast {
    get {_storage._forecast ?? Schedule.Forecast()}
    set {_uniqueStorage()._forecast = newValue}
  }
  /// Returns true if `forecast` has been explicitly set.
  public var hasForecast: Bool {_storage._forecast != nil}
  /// Clears the value of `forecast`. Subsequent reads from it will return its default value.
  public mutating func clearForecast() {_uniqueStorage()._forecast = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Forecast: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var isReverseFormation: Bool = false

    public var lateReason: DisruptionReason {
      get {_lateReason ?? DisruptionReason()}
      set {_lateReason = newValue}
    }
    /// Returns true if `lateReason` has been explicitly set.
    public var hasLateReason: Bool {self._lateReason != nil}
    /// Clears the value of `lateReason`. Subsequent reads from it will return its default value.
    public mutating func clearLateReason() {self._lateReason = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _lateReason: DisruptionReason? = nil
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Formation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var formationID: String = String()

  public var source: String {
    get {_source ?? String()}
    set {_source = newValue}
  }
  /// Returns true if `source` has been explicitly set.
  public var hasSource: Bool {self._source != nil}
  /// Clears the value of `source`. Subsequent reads from it will return its default value.
  public mutating func clearSource() {self._source = nil}

  public var sourceSystem: String {
    get {_sourceSystem ?? String()}
    set {_sourceSystem = newValue}
  }
  /// Returns true if `sourceSystem` has been explicitly set.
  public var hasSourceSystem: Bool {self._sourceSystem != nil}
  /// Clears the value of `sourceSystem`. Subsequent reads from it will return its default value.
  public mutating func clearSourceSystem() {self._sourceSystem = nil}

  public var coaches: [Formation.Coach] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Coach: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var identifier: String = String()

    public var `class`: String {
      get {_class ?? String()}
      set {_class = newValue}
    }
    /// Returns true if ``class`` has been explicitly set.
    public var hasClass: Bool {self._class != nil}
    /// Clears the value of ``class``. Subsequent reads from it will return its default value.
    public mutating func clearClass() {self._class = nil}

    public var toiletData: Formation.Coach.Toilet {
      get {_toiletData ?? Formation.Coach.Toilet()}
      set {_toiletData = newValue}
    }
    /// Returns true if `toiletData` has been explicitly set.
    public var hasToiletData: Bool {self._toiletData != nil}
    /// Clears the value of `toiletData`. Subsequent reads from it will return its default value.
    public mutating func clearToiletData() {self._toiletData = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public struct Toilet: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var type: String = String()

      public var status: Formation.Coach.Toilet.Status = .unknown

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public enum Status: SwiftProtobuf.Enum, Swift.CaseIterable {
        public typealias RawValue = Int
        case unknown // = 0
        case inService // = 1
        case notInService // = 2
        case UNRECOGNIZED(Int)

        public init() {
          self = .unknown
        }

        public init?(rawValue: Int) {
          switch rawValue {
          case 0: self = .unknown
          case 1: self = .inService
          case 2: self = .notInService
          default: self = .UNRECOGNIZED(rawValue)
          }
        }

        public var rawValue: Int {
          switch self {
          case .unknown: return 0
          case .inService: return 1
          case .notInService: return 2
          case .UNRECOGNIZED(let i): return i
          }
        }

        // The compiler won't synthesize support with the UNRECOGNIZED case.
        public static let allCases: [Formation.Coach.Toilet.Status] = [
          .unknown,
          .inService,
          .notInService,
        ]

      }

      public init() {}
    }

    public init() {}

    fileprivate var _class: String? = nil
    fileprivate var _toiletData: Formation.Coach.Toilet? = nil
  }

  public init() {}

  fileprivate var _source: String? = nil
  fileprivate var _sourceSystem: String? = nil
}

public struct ForecastLocation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var arrival: ForecastLocation.Times {
    get {_storage._arrival ?? ForecastLocation.Times()}
    set {_uniqueStorage()._arrival = newValue}
  }
  /// Returns true if `arrival` has been explicitly set.
  public var hasArrival: Bool {_storage._arrival != nil}
  /// Clears the value of `arrival`. Subsequent reads from it will return its default value.
  public mutating func clearArrival() {_uniqueStorage()._arrival = nil}

  public var passing: ForecastLocation.Times {
    get {_storage._passing ?? ForecastLocation.Times()}
    set {_uniqueStorage()._passing = newValue}
  }
  /// Returns true if `passing` has been explicitly set.
  public var hasPassing: Bool {_storage._passing != nil}
  /// Clears the value of `passing`. Subsequent reads from it will return its default value.
  public mutating func clearPassing() {_uniqueStorage()._passing = nil}

  public var departure: ForecastLocation.Times {
    get {_storage._departure ?? ForecastLocation.Times()}
    set {_uniqueStorage()._departure = newValue}
  }
  /// Returns true if `departure` has been explicitly set.
  public var hasDeparture: Bool {_storage._departure != nil}
  /// Clears the value of `departure`. Subsequent reads from it will return its default value.
  public mutating func clearDeparture() {_uniqueStorage()._departure = nil}

  public var lateReason: DisruptionReason {
    get {_storage._lateReason ?? DisruptionReason()}
    set {_uniqueStorage()._lateReason = newValue}
  }
  /// Returns true if `lateReason` has been explicitly set.
  public var hasLateReason: Bool {_storage._lateReason != nil}
  /// Clears the value of `lateReason`. Subsequent reads from it will return its default value.
  public mutating func clearLateReason() {_uniqueStorage()._lateReason = nil}

  public var disruptionRisk: String {
    get {_storage._disruptionRisk ?? String()}
    set {_uniqueStorage()._disruptionRisk = newValue}
  }
  /// Returns true if `disruptionRisk` has been explicitly set.
  public var hasDisruptionRisk: Bool {_storage._disruptionRisk != nil}
  /// Clears the value of `disruptionRisk`. Subsequent reads from it will return its default value.
  public mutating func clearDisruptionRisk() {_uniqueStorage()._disruptionRisk = nil}

  public var disruptionRiskReason: DisruptionReason {
    get {_storage._disruptionRiskReason ?? DisruptionReason()}
    set {_uniqueStorage()._disruptionRiskReason = newValue}
  }
  /// Returns true if `disruptionRiskReason` has been explicitly set.
  public var hasDisruptionRiskReason: Bool {_storage._disruptionRiskReason != nil}
  /// Clears the value of `disruptionRiskReason`. Subsequent reads from it will return its default value.
  public mutating func clearDisruptionRiskReason() {_uniqueStorage()._disruptionRiskReason = nil}

  public var affectedBy: String {
    get {_storage._affectedBy ?? String()}
    set {_uniqueStorage()._affectedBy = newValue}
  }
  /// Returns true if `affectedBy` has been explicitly set.
  public var hasAffectedBy: Bool {_storage._affectedBy != nil}
  /// Clears the value of `affectedBy`. Subsequent reads from it will return its default value.
  public mutating func clearAffectedBy() {_uniqueStorage()._affectedBy = nil}

  public var forecastLength: UInt32 {
    get {_storage._forecastLength ?? 0}
    set {_uniqueStorage()._forecastLength = newValue}
  }
  /// Returns true if `forecastLength` has been explicitly set.
  public var hasForecastLength: Bool {_storage._forecastLength != nil}
  /// Clears the value of `forecastLength`. Subsequent reads from it will return its default value.
  public mutating func clearForecastLength() {_uniqueStorage()._forecastLength = nil}

  public var forecastPlatform: ForecastLocation.Platform {
    get {_storage._forecastPlatform ?? ForecastLocation.Platform()}
    set {_uniqueStorage()._forecastPlatform = newValue}
  }
  /// Returns true if `forecastPlatform` has been explicitly set.
  public var hasForecastPlatform: Bool {_storage._forecastPlatform != nil}
  /// Clears the value of `forecastPlatform`. Subsequent reads from it will return its default value.
  public mutating func clearForecastPlatform() {_uniqueStorage()._forecastPlatform = nil}

  public var serviceIsSuppressedHere: Bool {
    get {_storage._serviceIsSuppressedHere}
    set {_uniqueStorage()._serviceIsSuppressedHere = newValue}
  }

  public var serviceDetachesFromFrontHere: Bool {
    get {_storage._serviceDetachesFromFrontHere}
    set {_uniqueStorage()._serviceDetachesFromFrontHere = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Times: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var estimatedPublicTime: String {
      get {_estimatedPublicTime ?? String()}
      set {_estimatedPublicTime = newValue}
    }
    /// Returns true if `estimatedPublicTime` has been explicitly set.
    public var hasEstimatedPublicTime: Bool {self._estimatedPublicTime != nil}
    /// Clears the value of `estimatedPublicTime`. Subsequent reads from it will return its default value.
    public mutating func clearEstimatedPublicTime() {self._estimatedPublicTime = nil}

    public var estimatedWorkingTime: String {
      get {_estimatedWorkingTime ?? String()}
      set {_estimatedWorkingTime = newValue}
    }
    /// Returns true if `estimatedWorkingTime` has been explicitly set.
    public var hasEstimatedWorkingTime: Bool {self._estimatedWorkingTime != nil}
    /// Clears the value of `estimatedWorkingTime`. Subsequent reads from it will return its default value.
    public mutating func clearEstimatedWorkingTime() {self._estimatedWorkingTime = nil}

    public var minimumEstimatedTime: String {
      get {_minimumEstimatedTime ?? String()}
      set {_minimumEstimatedTime = newValue}
    }
    /// Returns true if `minimumEstimatedTime` has been explicitly set.
    public var hasMinimumEstimatedTime: Bool {self._minimumEstimatedTime != nil}
    /// Clears the value of `minimumEstimatedTime`. Subsequent reads from it will return its default value.
    public mutating func clearMinimumEstimatedTime() {self._minimumEstimatedTime = nil}

    public var estimationManuallySetToDelayed: Bool = false

    public var estimatedAsDelayed: Bool = false

    public var actualTime: String {
      get {_actualTime ?? String()}
      set {_actualTime = newValue}
    }
    /// Returns true if `actualTime` has been explicitly set.
    public var hasActualTime: Bool {self._actualTime != nil}
    /// Clears the value of `actualTime`. Subsequent reads from it will return its default value.
    public mutating func clearActualTime() {self._actualTime = nil}

    public var actualTimeClass: String {
      get {_actualTimeClass ?? String()}
      set {_actualTimeClass = newValue}
    }
    /// Returns true if `actualTimeClass` has been explicitly set.
    public var hasActualTimeClass: Bool {self._actualTimeClass != nil}
    /// Clears the value of `actualTimeClass`. Subsequent reads from it will return its default value.
    public mutating func clearActualTimeClass() {self._actualTimeClass = nil}

    public var source: String {
      get {_source ?? String()}
      set {_source = newValue}
    }
    /// Returns true if `source` has been explicitly set.
    public var hasSource: Bool {self._source != nil}
    /// Clears the value of `source`. Subsequent reads from it will return its default value.
    public mutating func clearSource() {self._source = nil}

    public var sourceSystem: String {
      get {_sourceSystem ?? String()}
      set {_sourceSystem = newValue}
    }
    /// Returns true if `sourceSystem` has been explicitly set.
    public var hasSourceSystem: Bool {self._sourceSystem != nil}
    /// Clears the value of `sourceSystem`. Subsequent reads from it will return its default value.
    public mutating func clearSourceSystem() {self._sourceSystem = nil}

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _estimatedPublicTime: String? = nil
    fileprivate var _estimatedWorkingTime: String? = nil
    fileprivate var _minimumEstimatedTime: String? = nil
    fileprivate var _actualTime: String? = nil
    fileprivate var _actualTimeClass: String? = nil
    fileprivate var _source: String? = nil
    fileprivate var _sourceSystem: String? = nil
  }

  public struct Platform: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var isSuppressed: Bool = false

    public var isManuallySuppressedByCis: Bool = false

    public var source: String = String()

    public var isConfirmed: Bool = false

    public var platform: String = String()

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct FormationLoading: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var coaches: [FormationLoading.Coach] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Coach: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var identifier: String = String()

    public var source: String {
      get {_source ?? String()}
      set {_source = newValue}
    }
    /// Returns true if `source` has been explicitly set.
    public var hasSource: Bool {self._source != nil}
    /// Clears the value of `source`. Subsequent reads from it will return its default value.
    public mutating func clearSource() {self._source = nil}

    public var sourceSystem: String {
      get {_sourceSystem ?? String()}
      set {_sourceSystem = newValue}
    }
    /// Returns true if `sourceSystem` has been explicitly set.
    public var hasSourceSystem: Bool {self._sourceSystem != nil}
    /// Clears the value of `sourceSystem`. Subsequent reads from it will return its default value.
    public mutating func clearSourceSystem() {self._sourceSystem = nil}

    public var percentageLoad: UInt32 = 0

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _source: String? = nil
    fileprivate var _sourceSystem: String? = nil
  }

  public init() {}
}

/// 'Working' times are used internally by staff
/// 'Public' times are used for display to passengers
/// Working and Public timetables may differ, typically to allow services to experience very minor (30 to 60s) delays without appearing late to the public.
/// There is no scheduled_public_passing_time because locations through which a service passes without stopping do not need to display any times to the public.
public struct ScheduleLocation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scheduleUuid: String {
    get {_storage._scheduleUuid}
    set {_uniqueStorage()._scheduleUuid = newValue}
  }

  public var computedID: String {
    get {_storage._computedID}
    set {_uniqueStorage()._computedID = newValue}
  }

  public var locationID: String {
    get {_storage._locationID}
    set {_uniqueStorage()._locationID = newValue}
  }

  public var activities: [ActivityType] {
    get {_storage._activities}
    set {_uniqueStorage()._activities = newValue}
  }

  public var plannedActivities: [ActivityType] {
    get {_storage._plannedActivities}
    set {_uniqueStorage()._plannedActivities = newValue}
  }

  public var formationID: String {
    get {_storage._formationID ?? String()}
    set {_uniqueStorage()._formationID = newValue}
  }
  /// Returns true if `formationID` has been explicitly set.
  public var hasFormationID: Bool {_storage._formationID != nil}
  /// Clears the value of `formationID`. Subsequent reads from it will return its default value.
  public mutating func clearFormationID() {_uniqueStorage()._formationID = nil}

  public var isAffectedByDiversion: Bool {
    get {_storage._isAffectedByDiversion}
    set {_uniqueStorage()._isAffectedByDiversion = newValue}
  }

  public var type: ScheduleLocation.TypeEnum {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  public var workingArrivalTime: String {
    get {_storage._workingArrivalTime ?? String()}
    set {_uniqueStorage()._workingArrivalTime = newValue}
  }
  /// Returns true if `workingArrivalTime` has been explicitly set.
  public var hasWorkingArrivalTime: Bool {_storage._workingArrivalTime != nil}
  /// Clears the value of `workingArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearWorkingArrivalTime() {_uniqueStorage()._workingArrivalTime = nil}

  public var workingPassingTime: String {
    get {_storage._workingPassingTime ?? String()}
    set {_uniqueStorage()._workingPassingTime = newValue}
  }
  /// Returns true if `workingPassingTime` has been explicitly set.
  public var hasWorkingPassingTime: Bool {_storage._workingPassingTime != nil}
  /// Clears the value of `workingPassingTime`. Subsequent reads from it will return its default value.
  public mutating func clearWorkingPassingTime() {_uniqueStorage()._workingPassingTime = nil}

  public var workingDepartureTime: String {
    get {_storage._workingDepartureTime ?? String()}
    set {_uniqueStorage()._workingDepartureTime = newValue}
  }
  /// Returns true if `workingDepartureTime` has been explicitly set.
  public var hasWorkingDepartureTime: Bool {_storage._workingDepartureTime != nil}
  /// Clears the value of `workingDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearWorkingDepartureTime() {_uniqueStorage()._workingDepartureTime = nil}

  public var publicArrivalTime: String {
    get {_storage._publicArrivalTime ?? String()}
    set {_uniqueStorage()._publicArrivalTime = newValue}
  }
  /// Returns true if `publicArrivalTime` has been explicitly set.
  public var hasPublicArrivalTime: Bool {_storage._publicArrivalTime != nil}
  /// Clears the value of `publicArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearPublicArrivalTime() {_uniqueStorage()._publicArrivalTime = nil}

  public var publicDepartureTime: String {
    get {_storage._publicDepartureTime ?? String()}
    set {_uniqueStorage()._publicDepartureTime = newValue}
  }
  /// Returns true if `publicDepartureTime` has been explicitly set.
  public var hasPublicDepartureTime: Bool {_storage._publicDepartureTime != nil}
  /// Clears the value of `publicDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearPublicDepartureTime() {_uniqueStorage()._publicDepartureTime = nil}

  /// in minutes
  public var routingDelay: Int32 {
    get {_storage._routingDelay}
    set {_uniqueStorage()._routingDelay = newValue}
  }

  public var falseDestinationLocationID: String {
    get {_storage._falseDestinationLocationID ?? String()}
    set {_uniqueStorage()._falseDestinationLocationID = newValue}
  }
  /// Returns true if `falseDestinationLocationID` has been explicitly set.
  public var hasFalseDestinationLocationID: Bool {_storage._falseDestinationLocationID != nil}
  /// Clears the value of `falseDestinationLocationID`. Subsequent reads from it will return its default value.
  public mutating func clearFalseDestinationLocationID() {_uniqueStorage()._falseDestinationLocationID = nil}

  public var isCancelled: Bool {
    get {_storage._isCancelled}
    set {_uniqueStorage()._isCancelled = newValue}
  }

  public var locationCancellationReason: DisruptionReason {
    get {_storage._locationCancellationReason ?? DisruptionReason()}
    set {_uniqueStorage()._locationCancellationReason = newValue}
  }
  /// Returns true if `locationCancellationReason` has been explicitly set.
  public var hasLocationCancellationReason: Bool {_storage._locationCancellationReason != nil}
  /// Clears the value of `locationCancellationReason`. Subsequent reads from it will return its default value.
  public mutating func clearLocationCancellationReason() {_uniqueStorage()._locationCancellationReason = nil}

  public var timetabledPlatform: String {
    get {_storage._timetabledPlatform ?? String()}
    set {_uniqueStorage()._timetabledPlatform = newValue}
  }
  /// Returns true if `timetabledPlatform` has been explicitly set.
  public var hasTimetabledPlatform: Bool {_storage._timetabledPlatform != nil}
  /// Clears the value of `timetabledPlatform`. Subsequent reads from it will return its default value.
  public mutating func clearTimetabledPlatform() {_uniqueStorage()._timetabledPlatform = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TypeEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case locationUnknown // = 0
    case locationOrigin // = 1
    case locationOperationalOrigin // = 2
    case locationIntermediate // = 3
    case locationOperationalIntermediate // = 4
    case locationIntermediatePassing // = 5
    case locationDestination // = 6
    case locationOperationalDestination // = 7
    case UNRECOGNIZED(Int)

    public init() {
      self = .locationUnknown
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .locationUnknown
      case 1: self = .locationOrigin
      case 2: self = .locationOperationalOrigin
      case 3: self = .locationIntermediate
      case 4: self = .locationOperationalIntermediate
      case 5: self = .locationIntermediatePassing
      case 6: self = .locationDestination
      case 7: self = .locationOperationalDestination
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .locationUnknown: return 0
      case .locationOrigin: return 1
      case .locationOperationalOrigin: return 2
      case .locationIntermediate: return 3
      case .locationOperationalIntermediate: return 4
      case .locationIntermediatePassing: return 5
      case .locationDestination: return 6
      case .locationOperationalDestination: return 7
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [ScheduleLocation.TypeEnum] = [
      .locationUnknown,
      .locationOrigin,
      .locationOperationalOrigin,
      .locationIntermediate,
      .locationOperationalIntermediate,
      .locationIntermediatePassing,
      .locationDestination,
      .locationOperationalDestination,
    ]

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct ServiceLoading: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var category: ServiceLoading.Category {
    get {_category ?? ServiceLoading.Category()}
    set {_category = newValue}
  }
  /// Returns true if `category` has been explicitly set.
  public var hasCategory: Bool {self._category != nil}
  /// Clears the value of `category`. Subsequent reads from it will return its default value.
  public mutating func clearCategory() {self._category = nil}

  public var percentage: ServiceLoading.Percentage {
    get {_percentage ?? ServiceLoading.Percentage()}
    set {_percentage = newValue}
  }
  /// Returns true if `percentage` has been explicitly set.
  public var hasPercentage: Bool {self._percentage != nil}
  /// Clears the value of `percentage`. Subsequent reads from it will return its default value.
  public mutating func clearPercentage() {self._percentage = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum TypeEnum: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case loadingUnknown // = 0
    case loadingTypical // = 1
    case loadingExpected // = 2
    case UNRECOGNIZED(Int)

    public init() {
      self = .loadingUnknown
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .loadingUnknown
      case 1: self = .loadingTypical
      case 2: self = .loadingExpected
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .loadingUnknown: return 0
      case .loadingTypical: return 1
      case .loadingExpected: return 2
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [ServiceLoading.TypeEnum] = [
      .loadingUnknown,
      .loadingTypical,
      .loadingExpected,
    ]

  }

  public struct Category: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var code: String = String()

    public var source: String {
      get {_source ?? String()}
      set {_source = newValue}
    }
    /// Returns true if `source` has been explicitly set.
    public var hasSource: Bool {self._source != nil}
    /// Clears the value of `source`. Subsequent reads from it will return its default value.
    public mutating func clearSource() {self._source = nil}

    public var sourceSystem: String {
      get {_sourceSystem ?? String()}
      set {_sourceSystem = newValue}
    }
    /// Returns true if `sourceSystem` has been explicitly set.
    public var hasSourceSystem: Bool {self._sourceSystem != nil}
    /// Clears the value of `sourceSystem`. Subsequent reads from it will return its default value.
    public mutating func clearSourceSystem() {self._sourceSystem = nil}

    public var type: ServiceLoading.TypeEnum = .loadingUnknown

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _source: String? = nil
    fileprivate var _sourceSystem: String? = nil
  }

  public struct Percentage: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var percentageLoad: UInt32 = 0

    public var source: String {
      get {_source ?? String()}
      set {_source = newValue}
    }
    /// Returns true if `source` has been explicitly set.
    public var hasSource: Bool {self._source != nil}
    /// Clears the value of `source`. Subsequent reads from it will return its default value.
    public mutating func clearSource() {self._source = nil}

    public var sourceSystem: String {
      get {_sourceSystem ?? String()}
      set {_sourceSystem = newValue}
    }
    /// Returns true if `sourceSystem` has been explicitly set.
    public var hasSourceSystem: Bool {self._sourceSystem != nil}
    /// Clears the value of `sourceSystem`. Subsequent reads from it will return its default value.
    public mutating func clearSourceSystem() {self._sourceSystem = nil}

    public var type: ServiceLoading.TypeEnum = .loadingUnknown

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public init() {}

    fileprivate var _source: String? = nil
    fileprivate var _sourceSystem: String? = nil
  }

  public init() {}

  fileprivate var _category: ServiceLoading.Category? = nil
  fileprivate var _percentage: ServiceLoading.Percentage? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension DisruptionReason: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DisruptionReason"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}reason_id\0\u{3}reason_location_id\0\u{3}reason_is_near_location\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.reasonID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._reasonLocationID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.reasonIsNearLocation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.reasonID != 0 {
      try visitor.visitSingularUInt32Field(value: self.reasonID, fieldNumber: 1)
    }
    try { if let v = self._reasonLocationID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if self.reasonIsNearLocation != false {
      try visitor.visitSingularBoolField(value: self.reasonIsNearLocation, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DisruptionReason, rhs: DisruptionReason) -> Bool {
    if lhs.reasonID != rhs.reasonID {return false}
    if lhs._reasonLocationID != rhs._reasonLocationID {return false}
    if lhs.reasonIsNearLocation != rhs.reasonIsNearLocation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Schedule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "Schedule"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uuid\0\u{4}\u{3}schedule_id\0\u{1}uid\0\u{2}\u{3}headcode\0\u{3}retail_service_id\0\u{3}toc_id\0\u{1}service\0\u{1}category\0\u{3}is_passenger_service\0\u{3}is_active\0\u{4}\u{2}is_charter\0\u{3}is_cancelled\0\u{3}cancellation_reason\0\u{3}diverted_via_location_id\0\u{3}diversion_reason\0\u{1}forecast\0\u{c}\u{2}\u{2}\u{c}\u{6}\u{2}\u{c}\u{f}\u{1}")

  fileprivate class _StorageClass {
    var _uuid: String = String()
    var _scheduleID: String = String()
    var _uid: String = String()
    var _headcode: String = String()
    var _retailServiceID: String? = nil
    var _tocID: String = String()
    var _service: ServiceType = .serviceUnknown
    var _category: CategoryType = .categoryUnknown
    var _isPassengerService: Bool = false
    var _isActive: Bool = false
    var _isCharter: Bool = false
    var _isCancelled: Bool = false
    var _cancellationReason: DisruptionReason? = nil
    var _divertedViaLocationID: String? = nil
    var _diversionReason: DisruptionReason? = nil
    var _forecast: Schedule.Forecast? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _uuid = source._uuid
      _scheduleID = source._scheduleID
      _uid = source._uid
      _headcode = source._headcode
      _retailServiceID = source._retailServiceID
      _tocID = source._tocID
      _service = source._service
      _category = source._category
      _isPassengerService = source._isPassengerService
      _isActive = source._isActive
      _isCharter = source._isCharter
      _isCancelled = source._isCancelled
      _cancellationReason = source._cancellationReason
      _divertedViaLocationID = source._divertedViaLocationID
      _diversionReason = source._diversionReason
      _forecast = source._forecast
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._uuid) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._scheduleID) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._uid) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._headcode) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._retailServiceID) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._tocID) }()
        case 11: try { try decoder.decodeSingularEnumField(value: &_storage._service) }()
        case 12: try { try decoder.decodeSingularEnumField(value: &_storage._category) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._isPassengerService) }()
        case 14: try { try decoder.decodeSingularBoolField(value: &_storage._isActive) }()
        case 16: try { try decoder.decodeSingularBoolField(value: &_storage._isCharter) }()
        case 17: try { try decoder.decodeSingularBoolField(value: &_storage._isCancelled) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._cancellationReason) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._divertedViaLocationID) }()
        case 20: try { try decoder.decodeSingularMessageField(value: &_storage._diversionReason) }()
        case 21: try { try decoder.decodeSingularMessageField(value: &_storage._forecast) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._uuid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uuid, fieldNumber: 1)
      }
      if !_storage._scheduleID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scheduleID, fieldNumber: 4)
      }
      if !_storage._uid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uid, fieldNumber: 5)
      }
      if !_storage._headcode.isEmpty {
        try visitor.visitSingularStringField(value: _storage._headcode, fieldNumber: 8)
      }
      try { if let v = _storage._retailServiceID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      if !_storage._tocID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tocID, fieldNumber: 10)
      }
      if _storage._service != .serviceUnknown {
        try visitor.visitSingularEnumField(value: _storage._service, fieldNumber: 11)
      }
      if _storage._category != .categoryUnknown {
        try visitor.visitSingularEnumField(value: _storage._category, fieldNumber: 12)
      }
      if _storage._isPassengerService != false {
        try visitor.visitSingularBoolField(value: _storage._isPassengerService, fieldNumber: 13)
      }
      if _storage._isActive != false {
        try visitor.visitSingularBoolField(value: _storage._isActive, fieldNumber: 14)
      }
      if _storage._isCharter != false {
        try visitor.visitSingularBoolField(value: _storage._isCharter, fieldNumber: 16)
      }
      if _storage._isCancelled != false {
        try visitor.visitSingularBoolField(value: _storage._isCancelled, fieldNumber: 17)
      }
      try { if let v = _storage._cancellationReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._divertedViaLocationID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 19)
      } }()
      try { if let v = _storage._diversionReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      } }()
      try { if let v = _storage._forecast {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 21)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Schedule, rhs: Schedule) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._uuid != rhs_storage._uuid {return false}
        if _storage._scheduleID != rhs_storage._scheduleID {return false}
        if _storage._uid != rhs_storage._uid {return false}
        if _storage._headcode != rhs_storage._headcode {return false}
        if _storage._retailServiceID != rhs_storage._retailServiceID {return false}
        if _storage._tocID != rhs_storage._tocID {return false}
        if _storage._service != rhs_storage._service {return false}
        if _storage._category != rhs_storage._category {return false}
        if _storage._isPassengerService != rhs_storage._isPassengerService {return false}
        if _storage._isActive != rhs_storage._isActive {return false}
        if _storage._isCharter != rhs_storage._isCharter {return false}
        if _storage._isCancelled != rhs_storage._isCancelled {return false}
        if _storage._cancellationReason != rhs_storage._cancellationReason {return false}
        if _storage._divertedViaLocationID != rhs_storage._divertedViaLocationID {return false}
        if _storage._diversionReason != rhs_storage._diversionReason {return false}
        if _storage._forecast != rhs_storage._forecast {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Schedule.Forecast: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Schedule.protoMessageName + ".Forecast"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{4}is_reverse_formation\0\u{3}late_reason\0\u{c}\u{1}\u{3}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isReverseFormation) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._lateReason) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.isReverseFormation != false {
      try visitor.visitSingularBoolField(value: self.isReverseFormation, fieldNumber: 4)
    }
    try { if let v = self._lateReason {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Schedule.Forecast, rhs: Schedule.Forecast) -> Bool {
    if lhs.isReverseFormation != rhs.isReverseFormation {return false}
    if lhs._lateReason != rhs._lateReason {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Formation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "Formation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{4}formation_id\0\u{1}source\0\u{3}source_system\0\u{1}coaches\0\u{c}\u{1}\u{3}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 4: try { try decoder.decodeSingularStringField(value: &self.formationID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._sourceSystem) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.coaches) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.formationID.isEmpty {
      try visitor.visitSingularStringField(value: self.formationID, fieldNumber: 4)
    }
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._sourceSystem {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    if !self.coaches.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.coaches, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Formation, rhs: Formation) -> Bool {
    if lhs.formationID != rhs.formationID {return false}
    if lhs._source != rhs._source {return false}
    if lhs._sourceSystem != rhs._sourceSystem {return false}
    if lhs.coaches != rhs.coaches {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Formation.Coach: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Formation.protoMessageName + ".Coach"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}identifier\0\u{1}class\0\u{3}toilet_data\0\u{c}\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.identifier) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._class) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._toiletData) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.identifier.isEmpty {
      try visitor.visitSingularStringField(value: self.identifier, fieldNumber: 2)
    }
    try { if let v = self._class {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._toiletData {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Formation.Coach, rhs: Formation.Coach) -> Bool {
    if lhs.identifier != rhs.identifier {return false}
    if lhs._class != rhs._class {return false}
    if lhs._toiletData != rhs._toiletData {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Formation.Coach.Toilet: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = Formation.Coach.protoMessageName + ".Toilet"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}status\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.type) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.type.isEmpty {
      try visitor.visitSingularStringField(value: self.type, fieldNumber: 1)
    }
    if self.status != .unknown {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Formation.Coach.Toilet, rhs: Formation.Coach.Toilet) -> Bool {
    if lhs.type != rhs.type {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Formation.Coach.Toilet.Status: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0STATUS_UNKNOWN\0\u{1}STATUS_IN_SERVICE\0\u{1}STATUS_NOT_IN_SERVICE\0")
}

extension ForecastLocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ForecastLocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{9}arrival\0\u{1}passing\0\u{1}departure\0\u{3}late_reason\0\u{3}disruption_risk\0\u{3}disruption_risk_reason\0\u{3}affected_by\0\u{3}forecast_length\0\u{3}forecast_platform\0\u{3}service_is_suppressed_here\0\u{3}service_detaches_from_front_here\0\u{c}\u{1}\u{8}")

  fileprivate class _StorageClass {
    var _arrival: ForecastLocation.Times? = nil
    var _passing: ForecastLocation.Times? = nil
    var _departure: ForecastLocation.Times? = nil
    var _lateReason: DisruptionReason? = nil
    var _disruptionRisk: String? = nil
    var _disruptionRiskReason: DisruptionReason? = nil
    var _affectedBy: String? = nil
    var _forecastLength: UInt32? = nil
    var _forecastPlatform: ForecastLocation.Platform? = nil
    var _serviceIsSuppressedHere: Bool = false
    var _serviceDetachesFromFrontHere: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _arrival = source._arrival
      _passing = source._passing
      _departure = source._departure
      _lateReason = source._lateReason
      _disruptionRisk = source._disruptionRisk
      _disruptionRiskReason = source._disruptionRiskReason
      _affectedBy = source._affectedBy
      _forecastLength = source._forecastLength
      _forecastPlatform = source._forecastPlatform
      _serviceIsSuppressedHere = source._serviceIsSuppressedHere
      _serviceDetachesFromFrontHere = source._serviceDetachesFromFrontHere
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._arrival) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._passing) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._departure) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._lateReason) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._disruptionRisk) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._disruptionRiskReason) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._affectedBy) }()
        case 16: try { try decoder.decodeSingularUInt32Field(value: &_storage._forecastLength) }()
        case 17: try { try decoder.decodeSingularMessageField(value: &_storage._forecastPlatform) }()
        case 18: try { try decoder.decodeSingularBoolField(value: &_storage._serviceIsSuppressedHere) }()
        case 19: try { try decoder.decodeSingularBoolField(value: &_storage._serviceDetachesFromFrontHere) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._arrival {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._passing {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._departure {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._lateReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._disruptionRisk {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._disruptionRiskReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._affectedBy {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._forecastLength {
        try visitor.visitSingularUInt32Field(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._forecastPlatform {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
      } }()
      if _storage._serviceIsSuppressedHere != false {
        try visitor.visitSingularBoolField(value: _storage._serviceIsSuppressedHere, fieldNumber: 18)
      }
      if _storage._serviceDetachesFromFrontHere != false {
        try visitor.visitSingularBoolField(value: _storage._serviceDetachesFromFrontHere, fieldNumber: 19)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ForecastLocation, rhs: ForecastLocation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._arrival != rhs_storage._arrival {return false}
        if _storage._passing != rhs_storage._passing {return false}
        if _storage._departure != rhs_storage._departure {return false}
        if _storage._lateReason != rhs_storage._lateReason {return false}
        if _storage._disruptionRisk != rhs_storage._disruptionRisk {return false}
        if _storage._disruptionRiskReason != rhs_storage._disruptionRiskReason {return false}
        if _storage._affectedBy != rhs_storage._affectedBy {return false}
        if _storage._forecastLength != rhs_storage._forecastLength {return false}
        if _storage._forecastPlatform != rhs_storage._forecastPlatform {return false}
        if _storage._serviceIsSuppressedHere != rhs_storage._serviceIsSuppressedHere {return false}
        if _storage._serviceDetachesFromFrontHere != rhs_storage._serviceDetachesFromFrontHere {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ForecastLocation.Times: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = ForecastLocation.protoMessageName + ".Times"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}estimated_public_time\0\u{3}estimated_working_time\0\u{3}minimum_estimated_time\0\u{3}estimation_manually_set_to_delayed\0\u{3}estimated_as_delayed\0\u{3}actual_time\0\u{3}actual_time_class\0\u{1}source\0\u{3}source_system\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._estimatedPublicTime) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._estimatedWorkingTime) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._minimumEstimatedTime) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.estimationManuallySetToDelayed) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.estimatedAsDelayed) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._actualTime) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._actualTimeClass) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self._sourceSystem) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._estimatedPublicTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._estimatedWorkingTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._minimumEstimatedTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if self.estimationManuallySetToDelayed != false {
      try visitor.visitSingularBoolField(value: self.estimationManuallySetToDelayed, fieldNumber: 4)
    }
    if self.estimatedAsDelayed != false {
      try visitor.visitSingularBoolField(value: self.estimatedAsDelayed, fieldNumber: 5)
    }
    try { if let v = self._actualTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._actualTimeClass {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._sourceSystem {
      try visitor.visitSingularStringField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ForecastLocation.Times, rhs: ForecastLocation.Times) -> Bool {
    if lhs._estimatedPublicTime != rhs._estimatedPublicTime {return false}
    if lhs._estimatedWorkingTime != rhs._estimatedWorkingTime {return false}
    if lhs._minimumEstimatedTime != rhs._minimumEstimatedTime {return false}
    if lhs.estimationManuallySetToDelayed != rhs.estimationManuallySetToDelayed {return false}
    if lhs.estimatedAsDelayed != rhs.estimatedAsDelayed {return false}
    if lhs._actualTime != rhs._actualTime {return false}
    if lhs._actualTimeClass != rhs._actualTimeClass {return false}
    if lhs._source != rhs._source {return false}
    if lhs._sourceSystem != rhs._sourceSystem {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ForecastLocation.Platform: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = ForecastLocation.protoMessageName + ".Platform"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_suppressed\0\u{3}is_manually_suppressed_by_cis\0\u{1}source\0\u{3}is_confirmed\0\u{1}platform\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self.isSuppressed) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isManuallySuppressedByCis) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.source) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.isConfirmed) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self.platform) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.isSuppressed != false {
      try visitor.visitSingularBoolField(value: self.isSuppressed, fieldNumber: 1)
    }
    if self.isManuallySuppressedByCis != false {
      try visitor.visitSingularBoolField(value: self.isManuallySuppressedByCis, fieldNumber: 2)
    }
    if !self.source.isEmpty {
      try visitor.visitSingularStringField(value: self.source, fieldNumber: 3)
    }
    if self.isConfirmed != false {
      try visitor.visitSingularBoolField(value: self.isConfirmed, fieldNumber: 4)
    }
    if !self.platform.isEmpty {
      try visitor.visitSingularStringField(value: self.platform, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ForecastLocation.Platform, rhs: ForecastLocation.Platform) -> Bool {
    if lhs.isSuppressed != rhs.isSuppressed {return false}
    if lhs.isManuallySuppressedByCis != rhs.isManuallySuppressedByCis {return false}
    if lhs.source != rhs.source {return false}
    if lhs.isConfirmed != rhs.isConfirmed {return false}
    if lhs.platform != rhs.platform {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FormationLoading: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "FormationLoading"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{b}coaches\0\u{c}\u{1}\u{a}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 11: try { try decoder.decodeRepeatedMessageField(value: &self.coaches) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.coaches.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.coaches, fieldNumber: 11)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FormationLoading, rhs: FormationLoading) -> Bool {
    if lhs.coaches != rhs.coaches {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension FormationLoading.Coach: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = FormationLoading.protoMessageName + ".Coach"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{2}identifier\0\u{1}source\0\u{3}source_system\0\u{3}percentage_load\0\u{c}\u{1}\u{1}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 2: try { try decoder.decodeSingularStringField(value: &self.identifier) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._sourceSystem) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.percentageLoad) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.identifier.isEmpty {
      try visitor.visitSingularStringField(value: self.identifier, fieldNumber: 2)
    }
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._sourceSystem {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    if self.percentageLoad != 0 {
      try visitor.visitSingularUInt32Field(value: self.percentageLoad, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: FormationLoading.Coach, rhs: FormationLoading.Coach) -> Bool {
    if lhs.identifier != rhs.identifier {return false}
    if lhs._source != rhs._source {return false}
    if lhs._sourceSystem != rhs._sourceSystem {return false}
    if lhs.percentageLoad != rhs.percentageLoad {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ScheduleLocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ScheduleLocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{4}\u{2}schedule_uuid\0\u{3}computed_id\0\u{4}\u{2}location_id\0\u{1}activities\0\u{3}planned_activities\0\u{3}formation_id\0\u{3}is_affected_by_diversion\0\u{1}type\0\u{3}working_arrival_time\0\u{3}working_passing_time\0\u{3}working_departure_time\0\u{3}public_arrival_time\0\u{3}public_departure_time\0\u{3}routing_delay\0\u{3}false_destination_location_id\0\u{3}is_cancelled\0\u{3}location_cancellation_reason\0\u{3}timetabled_platform\0\u{c}\u{1}\u{1}\u{c}\u{4}\u{1}")

  fileprivate class _StorageClass {
    var _scheduleUuid: String = String()
    var _computedID: String = String()
    var _locationID: String = String()
    var _activities: [ActivityType] = []
    var _plannedActivities: [ActivityType] = []
    var _formationID: String? = nil
    var _isAffectedByDiversion: Bool = false
    var _type: ScheduleLocation.TypeEnum = .locationUnknown
    var _workingArrivalTime: String? = nil
    var _workingPassingTime: String? = nil
    var _workingDepartureTime: String? = nil
    var _publicArrivalTime: String? = nil
    var _publicDepartureTime: String? = nil
    var _routingDelay: Int32 = 0
    var _falseDestinationLocationID: String? = nil
    var _isCancelled: Bool = false
    var _locationCancellationReason: DisruptionReason? = nil
    var _timetabledPlatform: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _scheduleUuid = source._scheduleUuid
      _computedID = source._computedID
      _locationID = source._locationID
      _activities = source._activities
      _plannedActivities = source._plannedActivities
      _formationID = source._formationID
      _isAffectedByDiversion = source._isAffectedByDiversion
      _type = source._type
      _workingArrivalTime = source._workingArrivalTime
      _workingPassingTime = source._workingPassingTime
      _workingDepartureTime = source._workingDepartureTime
      _publicArrivalTime = source._publicArrivalTime
      _publicDepartureTime = source._publicDepartureTime
      _routingDelay = source._routingDelay
      _falseDestinationLocationID = source._falseDestinationLocationID
      _isCancelled = source._isCancelled
      _locationCancellationReason = source._locationCancellationReason
      _timetabledPlatform = source._timetabledPlatform
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._scheduleUuid) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._computedID) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._locationID) }()
        case 6: try { try decoder.decodeRepeatedEnumField(value: &_storage._activities) }()
        case 7: try { try decoder.decodeRepeatedEnumField(value: &_storage._plannedActivities) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._formationID) }()
        case 9: try { try decoder.decodeSingularBoolField(value: &_storage._isAffectedByDiversion) }()
        case 10: try { try decoder.decodeSingularEnumField(value: &_storage._type) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._workingArrivalTime) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._workingPassingTime) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._workingDepartureTime) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._publicArrivalTime) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._publicDepartureTime) }()
        case 16: try { try decoder.decodeSingularInt32Field(value: &_storage._routingDelay) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._falseDestinationLocationID) }()
        case 18: try { try decoder.decodeSingularBoolField(value: &_storage._isCancelled) }()
        case 19: try { try decoder.decodeSingularMessageField(value: &_storage._locationCancellationReason) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._timetabledPlatform) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._scheduleUuid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scheduleUuid, fieldNumber: 2)
      }
      if !_storage._computedID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._computedID, fieldNumber: 3)
      }
      if !_storage._locationID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._locationID, fieldNumber: 5)
      }
      if !_storage._activities.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._activities, fieldNumber: 6)
      }
      if !_storage._plannedActivities.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._plannedActivities, fieldNumber: 7)
      }
      try { if let v = _storage._formationID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      if _storage._isAffectedByDiversion != false {
        try visitor.visitSingularBoolField(value: _storage._isAffectedByDiversion, fieldNumber: 9)
      }
      if _storage._type != .locationUnknown {
        try visitor.visitSingularEnumField(value: _storage._type, fieldNumber: 10)
      }
      try { if let v = _storage._workingArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._workingPassingTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._workingDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._publicArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._publicDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
      if _storage._routingDelay != 0 {
        try visitor.visitSingularInt32Field(value: _storage._routingDelay, fieldNumber: 16)
      }
      try { if let v = _storage._falseDestinationLocationID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 17)
      } }()
      if _storage._isCancelled != false {
        try visitor.visitSingularBoolField(value: _storage._isCancelled, fieldNumber: 18)
      }
      try { if let v = _storage._locationCancellationReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 19)
      } }()
      try { if let v = _storage._timetabledPlatform {
        try visitor.visitSingularStringField(value: v, fieldNumber: 20)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ScheduleLocation, rhs: ScheduleLocation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._scheduleUuid != rhs_storage._scheduleUuid {return false}
        if _storage._computedID != rhs_storage._computedID {return false}
        if _storage._locationID != rhs_storage._locationID {return false}
        if _storage._activities != rhs_storage._activities {return false}
        if _storage._plannedActivities != rhs_storage._plannedActivities {return false}
        if _storage._formationID != rhs_storage._formationID {return false}
        if _storage._isAffectedByDiversion != rhs_storage._isAffectedByDiversion {return false}
        if _storage._type != rhs_storage._type {return false}
        if _storage._workingArrivalTime != rhs_storage._workingArrivalTime {return false}
        if _storage._workingPassingTime != rhs_storage._workingPassingTime {return false}
        if _storage._workingDepartureTime != rhs_storage._workingDepartureTime {return false}
        if _storage._publicArrivalTime != rhs_storage._publicArrivalTime {return false}
        if _storage._publicDepartureTime != rhs_storage._publicDepartureTime {return false}
        if _storage._routingDelay != rhs_storage._routingDelay {return false}
        if _storage._falseDestinationLocationID != rhs_storage._falseDestinationLocationID {return false}
        if _storage._isCancelled != rhs_storage._isCancelled {return false}
        if _storage._locationCancellationReason != rhs_storage._locationCancellationReason {return false}
        if _storage._timetabledPlatform != rhs_storage._timetabledPlatform {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ScheduleLocation.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TYPE_LOCATION_UNKNOWN\0\u{1}TYPE_LOCATION_ORIGIN\0\u{1}TYPE_LOCATION_OPERATIONAL_ORIGIN\0\u{1}TYPE_LOCATION_INTERMEDIATE\0\u{1}TYPE_LOCATION_OPERATIONAL_INTERMEDIATE\0\u{1}TYPE_LOCATION_INTERMEDIATE_PASSING\0\u{1}TYPE_LOCATION_DESTINATION\0\u{1}TYPE_LOCATION_OPERATIONAL_DESTINATION\0")
}

extension ServiceLoading: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ServiceLoading"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\u{a}category\0\u{1}percentage\0\u{c}\u{1}\u{9}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 10: try { try decoder.decodeSingularMessageField(value: &self._category) }()
      case 11: try { try decoder.decodeSingularMessageField(value: &self._percentage) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._category {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._percentage {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ServiceLoading, rhs: ServiceLoading) -> Bool {
    if lhs._category != rhs._category {return false}
    if lhs._percentage != rhs._percentage {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ServiceLoading.TypeEnum: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0TYPE_LOADING_UNKNOWN\0\u{1}TYPE_LOADING_TYPICAL\0\u{1}TYPE_LOADING_EXPECTED\0")
}

extension ServiceLoading.Category: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = ServiceLoading.protoMessageName + ".Category"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}code\0\u{1}source\0\u{3}source_system\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.code) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._sourceSystem) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.code.isEmpty {
      try visitor.visitSingularStringField(value: self.code, fieldNumber: 1)
    }
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._sourceSystem {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if self.type != .loadingUnknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ServiceLoading.Category, rhs: ServiceLoading.Category) -> Bool {
    if lhs.code != rhs.code {return false}
    if lhs._source != rhs._source {return false}
    if lhs._sourceSystem != rhs._sourceSystem {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ServiceLoading.Percentage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = ServiceLoading.protoMessageName + ".Percentage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}percentage_load\0\u{1}source\0\u{3}source_system\0\u{1}type\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.percentageLoad) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._source) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._sourceSystem) }()
      case 4: try { try decoder.decodeSingularEnumField(value: &self.type) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.percentageLoad != 0 {
      try visitor.visitSingularUInt32Field(value: self.percentageLoad, fieldNumber: 1)
    }
    try { if let v = self._source {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._sourceSystem {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if self.type != .loadingUnknown {
      try visitor.visitSingularEnumField(value: self.type, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ServiceLoading.Percentage, rhs: ServiceLoading.Percentage) -> Bool {
    if lhs.percentageLoad != rhs.percentageLoad {return false}
    if lhs._source != rhs._source {return false}
    if lhs._sourceSystem != rhs._sourceSystem {return false}
    if lhs.type != rhs.type {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
