// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: describeResponse.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct DescribeResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var request: DescribeRequest {
    get {_request ?? DescribeRequest()}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  public var schedules: [Schedule] = []

  public var formations: [Formation] = []

  public var route: [RouteLocation] = []

  public var originComputedIds: [Data] = []

  public var destinationComputedIds: [Data] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _request: DescribeRequest? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension DescribeResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DescribeResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}request\0\u{1}schedules\0\u{1}formations\0\u{1}route\0\u{3}origin_computed_ids\0\u{3}destination_computed_ids\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._request) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.schedules) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.formations) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.route) }()
      case 5: try { try decoder.decodeRepeatedBytesField(value: &self.originComputedIds) }()
      case 6: try { try decoder.decodeRepeatedBytesField(value: &self.destinationComputedIds) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.schedules.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.schedules, fieldNumber: 2)
    }
    if !self.formations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.formations, fieldNumber: 3)
    }
    if !self.route.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.route, fieldNumber: 4)
    }
    if !self.originComputedIds.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.originComputedIds, fieldNumber: 5)
    }
    if !self.destinationComputedIds.isEmpty {
      try visitor.visitRepeatedBytesField(value: self.destinationComputedIds, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DescribeResponse, rhs: DescribeResponse) -> Bool {
    if lhs._request != rhs._request {return false}
    if lhs.schedules != rhs.schedules {return false}
    if lhs.formations != rhs.formations {return false}
    if lhs.route != rhs.route {return false}
    if lhs.originComputedIds != rhs.originComputedIds {return false}
    if lhs.destinationComputedIds != rhs.destinationComputedIds {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
