// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: getLatestLocationUpdates.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct LatestLocationUpdatesRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// If not specified, all updates will be returned.
  public var currentReferenceFileID: String {
    get {_currentReferenceFileID ?? String()}
    set {_currentReferenceFileID = newValue}
  }
  /// Returns true if `currentReferenceFileID` has been explicitly set.
  public var hasCurrentReferenceFileID: Bool {self._currentReferenceFileID != nil}
  /// Clears the value of `currentReferenceFileID`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentReferenceFileID() {self._currentReferenceFileID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _currentReferenceFileID: String? = nil
}

public struct LatestLocationUpdatesResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// All (if any) updates between the current_reference_file_id in UpdateLocationsRequest and the new_reference_file_id in this response.
  public var updates: [LocationUpdate] = []

  /// The lastest reference_file_id equivalent you will have after applying all updates.
  public var newReferenceFileID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// An update made to a location at a point in time.
/// Provides the new state for a given location_id, and the reference_file_id at which this change occurred.
public struct LocationUpdate: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// The location_id affected
  public var locationID: String = String()

  /// The reference_file_id at which this change occurred. 
  public var referenceFileID: String = String()

  public var isDeleted: Bool = false

  public var crsID: String {
    get {_crsID ?? String()}
    set {_crsID = newValue}
  }
  /// Returns true if `crsID` has been explicitly set.
  public var hasCrsID: Bool {self._crsID != nil}
  /// Clears the value of `crsID`. Subsequent reads from it will return its default value.
  public mutating func clearCrsID() {self._crsID = nil}

  public var tocID: String {
    get {_tocID ?? String()}
    set {_tocID = newValue}
  }
  /// Returns true if `tocID` has been explicitly set.
  public var hasTocID: Bool {self._tocID != nil}
  /// Clears the value of `tocID`. Subsequent reads from it will return its default value.
  public mutating func clearTocID() {self._tocID = nil}

  public var name: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _crsID: String? = nil
  fileprivate var _tocID: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension LatestLocationUpdatesRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "LatestLocationUpdatesRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}current_reference_file_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._currentReferenceFileID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._currentReferenceFileID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: LatestLocationUpdatesRequest, rhs: LatestLocationUpdatesRequest) -> Bool {
    if lhs._currentReferenceFileID != rhs._currentReferenceFileID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LatestLocationUpdatesResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "LatestLocationUpdatesResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}updates\0\u{3}new_reference_file_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.updates) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.newReferenceFileID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.updates.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.updates, fieldNumber: 1)
    }
    if !self.newReferenceFileID.isEmpty {
      try visitor.visitSingularStringField(value: self.newReferenceFileID, fieldNumber: 2)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: LatestLocationUpdatesResponse, rhs: LatestLocationUpdatesResponse) -> Bool {
    if lhs.updates != rhs.updates {return false}
    if lhs.newReferenceFileID != rhs.newReferenceFileID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension LocationUpdate: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "LocationUpdate"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}location_id\0\u{3}reference_file_id\0\u{3}is_deleted\0\u{3}crs_id\0\u{3}toc_id\0\u{1}name\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.locationID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.referenceFileID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isDeleted) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._crsID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._tocID) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.locationID.isEmpty {
      try visitor.visitSingularStringField(value: self.locationID, fieldNumber: 1)
    }
    if !self.referenceFileID.isEmpty {
      try visitor.visitSingularStringField(value: self.referenceFileID, fieldNumber: 2)
    }
    if self.isDeleted != false {
      try visitor.visitSingularBoolField(value: self.isDeleted, fieldNumber: 3)
    }
    try { if let v = self._crsID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._tocID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: LocationUpdate, rhs: LocationUpdate) -> Bool {
    if lhs.locationID != rhs.locationID {return false}
    if lhs.referenceFileID != rhs.referenceFileID {return false}
    if lhs.isDeleted != rhs.isDeleted {return false}
    if lhs._crsID != rhs._crsID {return false}
    if lhs._tocID != rhs._tocID {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
