// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: overviewResponse.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct OverviewResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var request: OverviewRequest {
    get {_request ?? OverviewRequest()}
    set {_request = newValue}
  }
  /// Returns true if `request` has been explicitly set.
  public var hasRequest: Bool {self._request != nil}
  /// Clears the value of `request`. Subsequent reads from it will return its default value.
  public mutating func clearRequest() {self._request = nil}

  public var currentSchedule: Schedule {
    get {_currentSchedule ?? Schedule()}
    set {_currentSchedule = newValue}
  }
  /// Returns true if `currentSchedule` has been explicitly set.
  public var hasCurrentSchedule: Bool {self._currentSchedule != nil}
  /// Clears the value of `currentSchedule`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentSchedule() {self._currentSchedule = nil}

  public var currentFormation: Formation {
    get {_currentFormation ?? Formation()}
    set {_currentFormation = newValue}
  }
  /// Returns true if `currentFormation` has been explicitly set.
  public var hasCurrentFormation: Bool {self._currentFormation != nil}
  /// Clears the value of `currentFormation`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentFormation() {self._currentFormation = nil}

  public var currentRouteLocation: RouteLocation {
    get {_currentRouteLocation ?? RouteLocation()}
    set {_currentRouteLocation = newValue}
  }
  /// Returns true if `currentRouteLocation` has been explicitly set.
  public var hasCurrentRouteLocation: Bool {self._currentRouteLocation != nil}
  /// Clears the value of `currentRouteLocation`. Subsequent reads from it will return its default value.
  public mutating func clearCurrentRouteLocation() {self._currentRouteLocation = nil}

  public var originRouteLocations: [RouteLocation] = []

  public var destinationRouteLocations: [RouteLocation] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _request: OverviewRequest? = nil
  fileprivate var _currentSchedule: Schedule? = nil
  fileprivate var _currentFormation: Formation? = nil
  fileprivate var _currentRouteLocation: RouteLocation? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension OverviewResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "OverviewResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}request\0\u{3}current_schedule\0\u{3}current_formation\0\u{3}current_route_location\0\u{3}origin_route_locations\0\u{3}destination_route_locations\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._request) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._currentSchedule) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._currentFormation) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._currentRouteLocation) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.originRouteLocations) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.destinationRouteLocations) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._request {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._currentSchedule {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._currentFormation {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._currentRouteLocation {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    if !self.originRouteLocations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.originRouteLocations, fieldNumber: 5)
    }
    if !self.destinationRouteLocations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.destinationRouteLocations, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: OverviewResponse, rhs: OverviewResponse) -> Bool {
    if lhs._request != rhs._request {return false}
    if lhs._currentSchedule != rhs._currentSchedule {return false}
    if lhs._currentFormation != rhs._currentFormation {return false}
    if lhs._currentRouteLocation != rhs._currentRouteLocation {return false}
    if lhs.originRouteLocations != rhs.originRouteLocations {return false}
    if lhs.destinationRouteLocations != rhs.destinationRouteLocations {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
