// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: railreader.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - RailReader

/// Namespace containing generated types for the "RailReader" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum RailReader: Sendable {
    /// Service descriptor for the "RailReader" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetLocationUpdates" metadata.
        public enum GetLocationUpdates: Sendable {
            /// Request type for "GetLocationUpdates".
            public typealias Input = LocationUpdatesRequest
            /// Response type for "GetLocationUpdates".
            public typealias Output = LocationUpdateResponse
            /// Descriptor for "GetLocationUpdates".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "GetLocationUpdates"
            )
        }
        /// Namespace for "GetSchedulesAtLocation" metadata.
        public enum GetSchedulesAtLocation: Sendable {
            /// Request type for "GetSchedulesAtLocation".
            public typealias Input = SchedulesAtLocationRequest
            /// Response type for "GetSchedulesAtLocation".
            public typealias Output = SchedulesAtLocationResponse
            /// Descriptor for "GetSchedulesAtLocation".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "GetSchedulesAtLocation"
            )
        }
        /// Descriptors for all methods in the "RailReader" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetLocationUpdates.descriptor,
            GetSchedulesAtLocation.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "RailReader" service.
    public static let RailReader = GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader")
}

// MARK: RailReader (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader {
    /// Streaming variant of the service protocol for the "RailReader" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `LocationUpdatesRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `LocationUpdateResponse` messages.
        func getLocationUpdates(
            request: GRPCCore.StreamingServerRequest<LocationUpdatesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<LocationUpdateResponse>

        /// Handle the "GetSchedulesAtLocation" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SchedulesAtLocationRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SchedulesAtLocationResponse` messages.
        func getSchedulesAtLocation(
            request: GRPCCore.StreamingServerRequest<SchedulesAtLocationRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SchedulesAtLocationResponse>
    }

    /// Service protocol for the "RailReader" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: RailReader.StreamingServiceProtocol {
        /// Handle the "GetLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LocationUpdatesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `LocationUpdateResponse` message.
        func getLocationUpdates(
            request: GRPCCore.ServerRequest<LocationUpdatesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<LocationUpdateResponse>

        /// Handle the "GetSchedulesAtLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SchedulesAtLocationRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SchedulesAtLocationResponse` messages.
        func getSchedulesAtLocation(
            request: GRPCCore.ServerRequest<SchedulesAtLocationRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SchedulesAtLocationResponse>
    }

    /// Simple service protocol for the "RailReader" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: RailReader.ServiceProtocol {
        /// Handle the "GetLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A `LocationUpdatesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `LocationUpdateResponse` to respond with.
        func getLocationUpdates(
            request: LocationUpdatesRequest,
            context: GRPCCore.ServerContext
        ) async throws -> LocationUpdateResponse

        /// Handle the "GetSchedulesAtLocation" method.
        ///
        /// - Parameters:
        ///   - request: A `SchedulesAtLocationRequest` message.
        ///   - response: A response stream of `SchedulesAtLocationResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func getSchedulesAtLocation(
            request: SchedulesAtLocationRequest,
            response: GRPCCore.RPCWriter<SchedulesAtLocationResponse>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: RailReader.Method.GetLocationUpdates.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<LocationUpdatesRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<LocationUpdateResponse>(),
            handler: { request, context in
                try await self.getLocationUpdates(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RailReader.Method.GetSchedulesAtLocation.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SchedulesAtLocationRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SchedulesAtLocationResponse>(),
            handler: { request, context in
                try await self.getSchedulesAtLocation(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ServiceProtocol {
    public func getLocationUpdates(
        request: GRPCCore.StreamingServerRequest<LocationUpdatesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<LocationUpdateResponse> {
        let response = try await self.getLocationUpdates(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func getSchedulesAtLocation(
        request: GRPCCore.StreamingServerRequest<SchedulesAtLocationRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SchedulesAtLocationResponse> {
        let response = try await self.getSchedulesAtLocation(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.SimpleServiceProtocol {
    public func getLocationUpdates(
        request: GRPCCore.ServerRequest<LocationUpdatesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<LocationUpdateResponse> {
        return GRPCCore.ServerResponse<LocationUpdateResponse>(
            message: try await self.getLocationUpdates(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func getSchedulesAtLocation(
        request: GRPCCore.ServerRequest<SchedulesAtLocationRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SchedulesAtLocationResponse> {
        return GRPCCore.StreamingServerResponse<SchedulesAtLocationResponse>(
            metadata: [:],
            producer: { writer in
                try await self.getSchedulesAtLocation(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: RailReader (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader {
    /// Generated client protocol for the "RailReader" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LocationUpdatesRequest` message.
        ///   - serializer: A serializer for `LocationUpdatesRequest` messages.
        ///   - deserializer: A deserializer for `LocationUpdateResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getLocationUpdates<Result>(
            request: GRPCCore.ClientRequest<LocationUpdatesRequest>,
            serializer: some GRPCCore.MessageSerializer<LocationUpdatesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<LocationUpdateResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LocationUpdateResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetSchedulesAtLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SchedulesAtLocationRequest` message.
        ///   - serializer: A serializer for `SchedulesAtLocationRequest` messages.
        ///   - deserializer: A deserializer for `SchedulesAtLocationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getSchedulesAtLocation<Result>(
            request: GRPCCore.ClientRequest<SchedulesAtLocationRequest>,
            serializer: some GRPCCore.MessageSerializer<SchedulesAtLocationRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SchedulesAtLocationResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SchedulesAtLocationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "RailReader" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LocationUpdatesRequest` message.
        ///   - serializer: A serializer for `LocationUpdatesRequest` messages.
        ///   - deserializer: A deserializer for `LocationUpdateResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getLocationUpdates<Result>(
            request: GRPCCore.ClientRequest<LocationUpdatesRequest>,
            serializer: some GRPCCore.MessageSerializer<LocationUpdatesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<LocationUpdateResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LocationUpdateResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RailReader.Method.GetLocationUpdates.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetSchedulesAtLocation" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SchedulesAtLocationRequest` message.
        ///   - serializer: A serializer for `SchedulesAtLocationRequest` messages.
        ///   - deserializer: A deserializer for `SchedulesAtLocationResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getSchedulesAtLocation<Result>(
            request: GRPCCore.ClientRequest<SchedulesAtLocationRequest>,
            serializer: some GRPCCore.MessageSerializer<SchedulesAtLocationRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SchedulesAtLocationResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SchedulesAtLocationResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: RailReader.Method.GetSchedulesAtLocation.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ClientProtocol {
    /// Call the "GetLocationUpdates" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `LocationUpdatesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLocationUpdates<Result>(
        request: GRPCCore.ClientRequest<LocationUpdatesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LocationUpdateResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getLocationUpdates(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<LocationUpdatesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<LocationUpdateResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetSchedulesAtLocation" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SchedulesAtLocationRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getSchedulesAtLocation<Result>(
        request: GRPCCore.ClientRequest<SchedulesAtLocationRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SchedulesAtLocationResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.getSchedulesAtLocation(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SchedulesAtLocationRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SchedulesAtLocationResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ClientProtocol {
    /// Call the "GetLocationUpdates" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLocationUpdates<Result>(
        _ message: LocationUpdatesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LocationUpdateResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<LocationUpdatesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getLocationUpdates(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetSchedulesAtLocation" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getSchedulesAtLocation<Result>(
        _ message: SchedulesAtLocationRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<SchedulesAtLocationResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SchedulesAtLocationRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getSchedulesAtLocation(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}