// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: railreader.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - RailReader

/// Namespace containing generated types for the "RailReader" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum RailReader: Sendable {
    /// Service descriptor for the "RailReader" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "UpdateLocations" metadata.
        public enum UpdateLocations: Sendable {
            /// Request type for "UpdateLocations".
            public typealias Input = UpdateLocationsRequest
            /// Response type for "UpdateLocations".
            public typealias Output = UpdateLocationsResponse
            /// Descriptor for "UpdateLocations".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "UpdateLocations"
            )
        }
        /// Namespace for "Search" metadata.
        public enum Search: Sendable {
            /// Request type for "Search".
            public typealias Input = SearchRequest
            /// Response type for "Search".
            public typealias Output = SearchResponse
            /// Descriptor for "Search".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "Search"
            )
        }
        /// Namespace for "Describe" metadata.
        public enum Describe: Sendable {
            /// Request type for "Describe".
            public typealias Input = SearchResponse
            /// Response type for "Describe".
            public typealias Output = DescribeResponse
            /// Descriptor for "Describe".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "Describe"
            )
        }
        /// Descriptors for all methods in the "RailReader" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            UpdateLocations.descriptor,
            Search.descriptor,
            Describe.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "RailReader" service.
    public static let RailReader = GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader")
}

// MARK: RailReader (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader {
    /// Streaming variant of the service protocol for the "RailReader" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "UpdateLocations" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `UpdateLocationsRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `UpdateLocationsResponse` messages.
        func updateLocations(
            request: GRPCCore.StreamingServerRequest<UpdateLocationsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<UpdateLocationsResponse>

        /// Handle the "Search" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SearchRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `SearchResponse` messages.
        func search(
            request: GRPCCore.StreamingServerRequest<SearchRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<SearchResponse>

        /// Handle the "Describe" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SearchResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `DescribeResponse` messages.
        func describe(
            request: GRPCCore.StreamingServerRequest<SearchResponse>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<DescribeResponse>
    }

    /// Service protocol for the "RailReader" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: RailReader.StreamingServiceProtocol {
        /// Handle the "UpdateLocations" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateLocationsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `UpdateLocationsResponse` message.
        func updateLocations(
            request: GRPCCore.ServerRequest<UpdateLocationsRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<UpdateLocationsResponse>

        /// Handle the "Search" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SearchRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `SearchResponse` message.
        func search(
            request: GRPCCore.ServerRequest<SearchRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<SearchResponse>

        /// Handle the "Describe" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `SearchResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `DescribeResponse` messages.
        func describe(
            request: GRPCCore.StreamingServerRequest<SearchResponse>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<DescribeResponse>
    }

    /// Simple service protocol for the "RailReader" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: RailReader.ServiceProtocol {
        /// Handle the "UpdateLocations" method.
        ///
        /// - Parameters:
        ///   - request: A `UpdateLocationsRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `UpdateLocationsResponse` to respond with.
        func updateLocations(
            request: UpdateLocationsRequest,
            context: GRPCCore.ServerContext
        ) async throws -> UpdateLocationsResponse

        /// Handle the "Search" method.
        ///
        /// - Parameters:
        ///   - request: A `SearchRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `SearchResponse` to respond with.
        func search(
            request: SearchRequest,
            context: GRPCCore.ServerContext
        ) async throws -> SearchResponse

        /// Handle the "Describe" method.
        ///
        /// - Parameters:
        ///   - request: A stream of `SearchResponse` messages.
        ///   - response: A response stream of `DescribeResponse` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func describe(
            request: GRPCCore.RPCAsyncSequence<SearchResponse, any Swift.Error>,
            response: GRPCCore.RPCWriter<DescribeResponse>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: RailReader.Method.UpdateLocations.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateLocationsRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateLocationsResponse>(),
            handler: { request, context in
                try await self.updateLocations(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RailReader.Method.Search.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SearchRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<SearchResponse>(),
            handler: { request, context in
                try await self.search(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RailReader.Method.Describe.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<SearchResponse>(),
            serializer: GRPCProtobuf.ProtobufSerializer<DescribeResponse>(),
            handler: { request, context in
                try await self.describe(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ServiceProtocol {
    public func updateLocations(
        request: GRPCCore.StreamingServerRequest<UpdateLocationsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<UpdateLocationsResponse> {
        let response = try await self.updateLocations(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func search(
        request: GRPCCore.StreamingServerRequest<SearchRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<SearchResponse> {
        let response = try await self.search(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.SimpleServiceProtocol {
    public func updateLocations(
        request: GRPCCore.ServerRequest<UpdateLocationsRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<UpdateLocationsResponse> {
        return GRPCCore.ServerResponse<UpdateLocationsResponse>(
            message: try await self.updateLocations(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func search(
        request: GRPCCore.ServerRequest<SearchRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<SearchResponse> {
        return GRPCCore.ServerResponse<SearchResponse>(
            message: try await self.search(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func describe(
        request: GRPCCore.StreamingServerRequest<SearchResponse>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<DescribeResponse> {
        return GRPCCore.StreamingServerResponse<DescribeResponse>(
            metadata: [:],
            producer: { writer in
                try await self.describe(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: RailReader (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader {
    /// Generated client protocol for the "RailReader" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "UpdateLocations" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateLocationsRequest` message.
        ///   - serializer: A serializer for `UpdateLocationsRequest` messages.
        ///   - deserializer: A deserializer for `UpdateLocationsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func updateLocations<Result>(
            request: GRPCCore.ClientRequest<UpdateLocationsRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateLocationsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateLocationsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateLocationsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Search" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SearchRequest` message.
        ///   - serializer: A serializer for `SearchRequest` messages.
        ///   - deserializer: A deserializer for `SearchResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func search<Result>(
            request: GRPCCore.ClientRequest<SearchRequest>,
            serializer: some GRPCCore.MessageSerializer<SearchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SearchResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SearchResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Describe" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `SearchResponse` messages.
        ///   - serializer: A serializer for `SearchResponse` messages.
        ///   - deserializer: A deserializer for `DescribeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func describe<Result>(
            request: GRPCCore.StreamingClientRequest<SearchResponse>,
            serializer: some GRPCCore.MessageSerializer<SearchResponse>,
            deserializer: some GRPCCore.MessageDeserializer<DescribeResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<DescribeResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "RailReader" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "UpdateLocations" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `UpdateLocationsRequest` message.
        ///   - serializer: A serializer for `UpdateLocationsRequest` messages.
        ///   - deserializer: A deserializer for `UpdateLocationsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func updateLocations<Result>(
            request: GRPCCore.ClientRequest<UpdateLocationsRequest>,
            serializer: some GRPCCore.MessageSerializer<UpdateLocationsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<UpdateLocationsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateLocationsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RailReader.Method.UpdateLocations.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Search" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `SearchRequest` message.
        ///   - serializer: A serializer for `SearchRequest` messages.
        ///   - deserializer: A deserializer for `SearchResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func search<Result>(
            request: GRPCCore.ClientRequest<SearchRequest>,
            serializer: some GRPCCore.MessageSerializer<SearchRequest>,
            deserializer: some GRPCCore.MessageDeserializer<SearchResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SearchResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RailReader.Method.Search.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Describe" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `SearchResponse` messages.
        ///   - serializer: A serializer for `SearchResponse` messages.
        ///   - deserializer: A deserializer for `DescribeResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func describe<Result>(
            request: GRPCCore.StreamingClientRequest<SearchResponse>,
            serializer: some GRPCCore.MessageSerializer<SearchResponse>,
            deserializer: some GRPCCore.MessageDeserializer<DescribeResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<DescribeResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: RailReader.Method.Describe.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ClientProtocol {
    /// Call the "UpdateLocations" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `UpdateLocationsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateLocations<Result>(
        request: GRPCCore.ClientRequest<UpdateLocationsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateLocationsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.updateLocations(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<UpdateLocationsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<UpdateLocationsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Search" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `SearchRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func search<Result>(
        request: GRPCCore.ClientRequest<SearchRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SearchResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.search(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SearchRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<SearchResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Describe" method.
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `SearchResponse` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func describe<Result>(
        request: GRPCCore.StreamingClientRequest<SearchResponse>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<DescribeResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.describe(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<SearchResponse>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<DescribeResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ClientProtocol {
    /// Call the "UpdateLocations" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func updateLocations<Result>(
        _ message: UpdateLocationsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<UpdateLocationsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<UpdateLocationsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.updateLocations(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Search" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func search<Result>(
        _ message: SearchRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<SearchResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<SearchRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.search(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Describe" method.
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func describe<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<SearchResponse>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<DescribeResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<SearchResponse>(
            metadata: metadata,
            producer: producer
        )
        return try await self.describe(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}