// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: railreader.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - RailReader

/// Namespace containing generated types for the "RailReader" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum RailReader: Sendable {
    /// Service descriptor for the "RailReader" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "GetLatestLocationUpdates" metadata.
        public enum GetLatestLocationUpdates: Sendable {
            /// Request type for "GetLatestLocationUpdates".
            public typealias Input = LatestLocationUpdatesRequest
            /// Response type for "GetLatestLocationUpdates".
            public typealias Output = LatestLocationUpdatesResponse
            /// Descriptor for "GetLatestLocationUpdates".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "GetLatestLocationUpdates"
            )
        }
        /// Namespace for "ListSchedulesAtLocationID" metadata.
        public enum ListSchedulesAtLocationID: Sendable {
            /// Request type for "ListSchedulesAtLocationID".
            public typealias Input = ListSchedulesAtLocationIDRequest
            /// Response type for "ListSchedulesAtLocationID".
            public typealias Output = ScheduleLocationUUID
            /// Descriptor for "ListSchedulesAtLocationID".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "ListSchedulesAtLocationID"
            )
        }
        /// Namespace for "DescribeSchedulesByScheduleLocationUUID" metadata.
        public enum DescribeSchedulesByScheduleLocationUUID: Sendable {
            /// Request type for "DescribeSchedulesByScheduleLocationUUID".
            public typealias Input = DescribeScheduleByScheduleLocationUUIDRequest
            /// Response type for "DescribeSchedulesByScheduleLocationUUID".
            public typealias Output = ServiceDescription
            /// Descriptor for "DescribeSchedulesByScheduleLocationUUID".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader"),
                method: "DescribeSchedulesByScheduleLocationUUID"
            )
        }
        /// Descriptors for all methods in the "RailReader" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            GetLatestLocationUpdates.descriptor,
            ListSchedulesAtLocationID.descriptor,
            DescribeSchedulesByScheduleLocationUUID.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "RailReader" service.
    public static let RailReader = GRPCCore.ServiceDescriptor(fullyQualifiedService: "RailReader")
}

// MARK: RailReader (server)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader {
    /// Streaming variant of the service protocol for the "RailReader" service.
    ///
    /// This protocol is the lowest-level of the service protocols generated for this service
    /// giving you the most flexibility over the implementation of your service. This comes at
    /// the cost of more verbose and less strict APIs. Each RPC requires you to implement it in
    /// terms of a request stream and response stream. Where only a single request or response
    /// message is expected, you are responsible for enforcing this invariant is maintained.
    ///
    /// Where possible, prefer using the stricter, less-verbose ``ServiceProtocol``
    /// or ``SimpleServiceProtocol`` instead.
    public protocol StreamingServiceProtocol: GRPCCore.RegistrableRPCService {
        /// Handle the "GetLatestLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `LatestLocationUpdatesRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `LatestLocationUpdatesResponse` messages.
        func getLatestLocationUpdates(
            request: GRPCCore.StreamingServerRequest<LatestLocationUpdatesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<LatestLocationUpdatesResponse>

        /// Handle the "ListSchedulesAtLocationID" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `ListSchedulesAtLocationIDRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `ScheduleLocationUUID` messages.
        func listSchedulesAtLocationID(
            request: GRPCCore.StreamingServerRequest<ListSchedulesAtLocationIDRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<ScheduleLocationUUID>

        /// Handle the "DescribeSchedulesByScheduleLocationUUID" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `DescribeScheduleByScheduleLocationUUIDRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `ServiceDescription` messages.
        func describeSchedulesByScheduleLocationUUID(
            request: GRPCCore.StreamingServerRequest<DescribeScheduleByScheduleLocationUUIDRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<ServiceDescription>
    }

    /// Service protocol for the "RailReader" service.
    ///
    /// This protocol is higher level than ``StreamingServiceProtocol`` but lower level than
    /// the ``SimpleServiceProtocol``, it provides access to request and response metadata and
    /// trailing response metadata. If you don't need these then consider using
    /// the ``SimpleServiceProtocol``. If you need fine grained control over your RPCs then
    /// use ``StreamingServiceProtocol``.
    public protocol ServiceProtocol: RailReader.StreamingServiceProtocol {
        /// Handle the "GetLatestLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LatestLocationUpdatesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A response containing a single `LatestLocationUpdatesResponse` message.
        func getLatestLocationUpdates(
            request: GRPCCore.ServerRequest<LatestLocationUpdatesRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.ServerResponse<LatestLocationUpdatesResponse>

        /// Handle the "ListSchedulesAtLocationID" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ListSchedulesAtLocationIDRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `ScheduleLocationUUID` messages.
        func listSchedulesAtLocationID(
            request: GRPCCore.ServerRequest<ListSchedulesAtLocationIDRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<ScheduleLocationUUID>

        /// Handle the "DescribeSchedulesByScheduleLocationUUID" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request of `DescribeScheduleByScheduleLocationUUIDRequest` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A streaming response of `ServiceDescription` messages.
        func describeSchedulesByScheduleLocationUUID(
            request: GRPCCore.StreamingServerRequest<DescribeScheduleByScheduleLocationUUIDRequest>,
            context: GRPCCore.ServerContext
        ) async throws -> GRPCCore.StreamingServerResponse<ServiceDescription>
    }

    /// Simple service protocol for the "RailReader" service.
    ///
    /// This is the highest level protocol for the service. The API is the easiest to use but
    /// doesn't provide access to request or response metadata. If you need access to these
    /// then use ``ServiceProtocol`` instead.
    public protocol SimpleServiceProtocol: RailReader.ServiceProtocol {
        /// Handle the "GetLatestLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A `LatestLocationUpdatesRequest` message.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        /// - Returns: A `LatestLocationUpdatesResponse` to respond with.
        func getLatestLocationUpdates(
            request: LatestLocationUpdatesRequest,
            context: GRPCCore.ServerContext
        ) async throws -> LatestLocationUpdatesResponse

        /// Handle the "ListSchedulesAtLocationID" method.
        ///
        /// - Parameters:
        ///   - request: A `ListSchedulesAtLocationIDRequest` message.
        ///   - response: A response stream of `ScheduleLocationUUID` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func listSchedulesAtLocationID(
            request: ListSchedulesAtLocationIDRequest,
            response: GRPCCore.RPCWriter<ScheduleLocationUUID>,
            context: GRPCCore.ServerContext
        ) async throws

        /// Handle the "DescribeSchedulesByScheduleLocationUUID" method.
        ///
        /// - Parameters:
        ///   - request: A stream of `DescribeScheduleByScheduleLocationUUIDRequest` messages.
        ///   - response: A response stream of `ServiceDescription` messages.
        ///   - context: Context providing information about the RPC.
        /// - Throws: Any error which occurred during the processing of the request. Thrown errors
        ///     of type `RPCError` are mapped to appropriate statuses. All other errors are converted
        ///     to an internal error.
        func describeSchedulesByScheduleLocationUUID(
            request: GRPCCore.RPCAsyncSequence<DescribeScheduleByScheduleLocationUUIDRequest, any Swift.Error>,
            response: GRPCCore.RPCWriter<ServiceDescription>,
            context: GRPCCore.ServerContext
        ) async throws
    }
}

// Default implementation of 'registerMethods(with:)'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.StreamingServiceProtocol {
    public func registerMethods<Transport>(with router: inout GRPCCore.RPCRouter<Transport>) where Transport: GRPCCore.ServerTransport {
        router.registerHandler(
            forMethod: RailReader.Method.GetLatestLocationUpdates.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<LatestLocationUpdatesRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<LatestLocationUpdatesResponse>(),
            handler: { request, context in
                try await self.getLatestLocationUpdates(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RailReader.Method.ListSchedulesAtLocationID.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<ListSchedulesAtLocationIDRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<ScheduleLocationUUID>(),
            handler: { request, context in
                try await self.listSchedulesAtLocationID(
                    request: request,
                    context: context
                )
            }
        )
        router.registerHandler(
            forMethod: RailReader.Method.DescribeSchedulesByScheduleLocationUUID.descriptor,
            deserializer: GRPCProtobuf.ProtobufDeserializer<DescribeScheduleByScheduleLocationUUIDRequest>(),
            serializer: GRPCProtobuf.ProtobufSerializer<ServiceDescription>(),
            handler: { request, context in
                try await self.describeSchedulesByScheduleLocationUUID(
                    request: request,
                    context: context
                )
            }
        )
    }
}

// Default implementation of streaming methods from 'StreamingServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ServiceProtocol {
    public func getLatestLocationUpdates(
        request: GRPCCore.StreamingServerRequest<LatestLocationUpdatesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<LatestLocationUpdatesResponse> {
        let response = try await self.getLatestLocationUpdates(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return GRPCCore.StreamingServerResponse(single: response)
    }

    public func listSchedulesAtLocationID(
        request: GRPCCore.StreamingServerRequest<ListSchedulesAtLocationIDRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<ScheduleLocationUUID> {
        let response = try await self.listSchedulesAtLocationID(
            request: GRPCCore.ServerRequest(stream: request),
            context: context
        )
        return response
    }
}

// Default implementation of methods from 'ServiceProtocol'.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.SimpleServiceProtocol {
    public func getLatestLocationUpdates(
        request: GRPCCore.ServerRequest<LatestLocationUpdatesRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.ServerResponse<LatestLocationUpdatesResponse> {
        return GRPCCore.ServerResponse<LatestLocationUpdatesResponse>(
            message: try await self.getLatestLocationUpdates(
                request: request.message,
                context: context
            ),
            metadata: [:]
        )
    }

    public func listSchedulesAtLocationID(
        request: GRPCCore.ServerRequest<ListSchedulesAtLocationIDRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<ScheduleLocationUUID> {
        return GRPCCore.StreamingServerResponse<ScheduleLocationUUID>(
            metadata: [:],
            producer: { writer in
                try await self.listSchedulesAtLocationID(
                    request: request.message,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }

    public func describeSchedulesByScheduleLocationUUID(
        request: GRPCCore.StreamingServerRequest<DescribeScheduleByScheduleLocationUUIDRequest>,
        context: GRPCCore.ServerContext
    ) async throws -> GRPCCore.StreamingServerResponse<ServiceDescription> {
        return GRPCCore.StreamingServerResponse<ServiceDescription>(
            metadata: [:],
            producer: { writer in
                try await self.describeSchedulesByScheduleLocationUUID(
                    request: request.messages,
                    response: writer,
                    context: context
                )
                return [:]
            }
        )
    }
}

// MARK: RailReader (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader {
    /// Generated client protocol for the "RailReader" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "GetLatestLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LatestLocationUpdatesRequest` message.
        ///   - serializer: A serializer for `LatestLocationUpdatesRequest` messages.
        ///   - deserializer: A deserializer for `LatestLocationUpdatesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getLatestLocationUpdates<Result>(
            request: GRPCCore.ClientRequest<LatestLocationUpdatesRequest>,
            serializer: some GRPCCore.MessageSerializer<LatestLocationUpdatesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<LatestLocationUpdatesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LatestLocationUpdatesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListSchedulesAtLocationID" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ListSchedulesAtLocationIDRequest` message.
        ///   - serializer: A serializer for `ListSchedulesAtLocationIDRequest` messages.
        ///   - deserializer: A deserializer for `ScheduleLocationUUID` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listSchedulesAtLocationID<Result>(
            request: GRPCCore.ClientRequest<ListSchedulesAtLocationIDRequest>,
            serializer: some GRPCCore.MessageSerializer<ListSchedulesAtLocationIDRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ScheduleLocationUUID>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ScheduleLocationUUID>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DescribeSchedulesByScheduleLocationUUID" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `DescribeScheduleByScheduleLocationUUIDRequest` messages.
        ///   - serializer: A serializer for `DescribeScheduleByScheduleLocationUUIDRequest` messages.
        ///   - deserializer: A deserializer for `ServiceDescription` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func describeSchedulesByScheduleLocationUUID<Result>(
            request: GRPCCore.StreamingClientRequest<DescribeScheduleByScheduleLocationUUIDRequest>,
            serializer: some GRPCCore.MessageSerializer<DescribeScheduleByScheduleLocationUUIDRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ServiceDescription>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ServiceDescription>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "RailReader" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "GetLatestLocationUpdates" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `LatestLocationUpdatesRequest` message.
        ///   - serializer: A serializer for `LatestLocationUpdatesRequest` messages.
        ///   - deserializer: A deserializer for `LatestLocationUpdatesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getLatestLocationUpdates<Result>(
            request: GRPCCore.ClientRequest<LatestLocationUpdatesRequest>,
            serializer: some GRPCCore.MessageSerializer<LatestLocationUpdatesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<LatestLocationUpdatesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LatestLocationUpdatesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: RailReader.Method.GetLatestLocationUpdates.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListSchedulesAtLocationID" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `ListSchedulesAtLocationIDRequest` message.
        ///   - serializer: A serializer for `ListSchedulesAtLocationIDRequest` messages.
        ///   - deserializer: A deserializer for `ScheduleLocationUUID` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listSchedulesAtLocationID<Result>(
            request: GRPCCore.ClientRequest<ListSchedulesAtLocationIDRequest>,
            serializer: some GRPCCore.MessageSerializer<ListSchedulesAtLocationIDRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ScheduleLocationUUID>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ScheduleLocationUUID>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: RailReader.Method.ListSchedulesAtLocationID.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DescribeSchedulesByScheduleLocationUUID" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `DescribeScheduleByScheduleLocationUUIDRequest` messages.
        ///   - serializer: A serializer for `DescribeScheduleByScheduleLocationUUIDRequest` messages.
        ///   - deserializer: A deserializer for `ServiceDescription` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func describeSchedulesByScheduleLocationUUID<Result>(
            request: GRPCCore.StreamingClientRequest<DescribeScheduleByScheduleLocationUUIDRequest>,
            serializer: some GRPCCore.MessageSerializer<DescribeScheduleByScheduleLocationUUIDRequest>,
            deserializer: some GRPCCore.MessageDeserializer<ServiceDescription>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ServiceDescription>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: RailReader.Method.DescribeSchedulesByScheduleLocationUUID.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ClientProtocol {
    /// Call the "GetLatestLocationUpdates" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `LatestLocationUpdatesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLatestLocationUpdates<Result>(
        request: GRPCCore.ClientRequest<LatestLocationUpdatesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LatestLocationUpdatesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getLatestLocationUpdates(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<LatestLocationUpdatesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<LatestLocationUpdatesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListSchedulesAtLocationID" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `ListSchedulesAtLocationIDRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listSchedulesAtLocationID<Result>(
        request: GRPCCore.ClientRequest<ListSchedulesAtLocationIDRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ScheduleLocationUUID>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.listSchedulesAtLocationID(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<ListSchedulesAtLocationIDRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ScheduleLocationUUID>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DescribeSchedulesByScheduleLocationUUID" method.
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `DescribeScheduleByScheduleLocationUUIDRequest` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func describeSchedulesByScheduleLocationUUID<Result>(
        request: GRPCCore.StreamingClientRequest<DescribeScheduleByScheduleLocationUUIDRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ServiceDescription>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.describeSchedulesByScheduleLocationUUID(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<DescribeScheduleByScheduleLocationUUIDRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<ServiceDescription>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension RailReader.ClientProtocol {
    /// Call the "GetLatestLocationUpdates" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getLatestLocationUpdates<Result>(
        _ message: LatestLocationUpdatesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<LatestLocationUpdatesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<LatestLocationUpdatesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getLatestLocationUpdates(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListSchedulesAtLocationID" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listSchedulesAtLocationID<Result>(
        _ message: ListSchedulesAtLocationIDRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ScheduleLocationUUID>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<ListSchedulesAtLocationIDRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listSchedulesAtLocationID(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DescribeSchedulesByScheduleLocationUUID" method.
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func describeSchedulesByScheduleLocationUUID<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<DescribeScheduleByScheduleLocationUUIDRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<ServiceDescription>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<DescribeScheduleByScheduleLocationUUIDRequest>(
            metadata: metadata,
            producer: producer
        )
        return try await self.describeSchedulesByScheduleLocationUUID(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}