// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: routeLocation.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

#if canImport(FoundationEssentials)
import FoundationEssentials
#else
import Foundation
#endif
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct RouteLocation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nextEdges: [RouteLocation.Edge] {
    get {_storage._nextEdges}
    set {_uniqueStorage()._nextEdges = newValue}
  }

  public var previousEdges: [RouteLocation.Edge] {
    get {_storage._previousEdges}
    set {_uniqueStorage()._previousEdges = newValue}
  }

  public var viaText: String {
    get {_storage._viaText ?? String()}
    set {_uniqueStorage()._viaText = newValue}
  }
  /// Returns true if `viaText` has been explicitly set.
  public var hasViaText: Bool {_storage._viaText != nil}
  /// Clears the value of `viaText`. Subsequent reads from it will return its default value.
  public mutating func clearViaText() {_uniqueStorage()._viaText = nil}

  public var forecastLocation: ForecastLocation {
    get {_storage._forecastLocation ?? ForecastLocation()}
    set {_uniqueStorage()._forecastLocation = newValue}
  }
  /// Returns true if `forecastLocation` has been explicitly set.
  public var hasForecastLocation: Bool {_storage._forecastLocation != nil}
  /// Clears the value of `forecastLocation`. Subsequent reads from it will return its default value.
  public mutating func clearForecastLocation() {_uniqueStorage()._forecastLocation = nil}

  public var formationLoading: FormationLoading {
    get {_storage._formationLoading ?? FormationLoading()}
    set {_uniqueStorage()._formationLoading = newValue}
  }
  /// Returns true if `formationLoading` has been explicitly set.
  public var hasFormationLoading: Bool {_storage._formationLoading != nil}
  /// Clears the value of `formationLoading`. Subsequent reads from it will return its default value.
  public mutating func clearFormationLoading() {_uniqueStorage()._formationLoading = nil}

  public var scheduleLocation: ScheduleLocation {
    get {_storage._scheduleLocation ?? ScheduleLocation()}
    set {_uniqueStorage()._scheduleLocation = newValue}
  }
  /// Returns true if `scheduleLocation` has been explicitly set.
  public var hasScheduleLocation: Bool {_storage._scheduleLocation != nil}
  /// Clears the value of `scheduleLocation`. Subsequent reads from it will return its default value.
  public mutating func clearScheduleLocation() {_uniqueStorage()._scheduleLocation = nil}

  public var serviceLoading: ServiceLoading {
    get {_storage._serviceLoading ?? ServiceLoading()}
    set {_uniqueStorage()._serviceLoading = newValue}
  }
  /// Returns true if `serviceLoading` has been explicitly set.
  public var hasServiceLoading: Bool {_storage._serviceLoading != nil}
  /// Clears the value of `serviceLoading`. Subsequent reads from it will return its default value.
  public mutating func clearServiceLoading() {_uniqueStorage()._serviceLoading = nil}

  public var generousArrivalTime: String {
    get {_storage._generousArrivalTime ?? String()}
    set {_uniqueStorage()._generousArrivalTime = newValue}
  }
  /// Returns true if `generousArrivalTime` has been explicitly set.
  public var hasGenerousArrivalTime: Bool {_storage._generousArrivalTime != nil}
  /// Clears the value of `generousArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearGenerousArrivalTime() {_uniqueStorage()._generousArrivalTime = nil}

  public var generousPassingTime: String {
    get {_storage._generousPassingTime ?? String()}
    set {_uniqueStorage()._generousPassingTime = newValue}
  }
  /// Returns true if `generousPassingTime` has been explicitly set.
  public var hasGenerousPassingTime: Bool {_storage._generousPassingTime != nil}
  /// Clears the value of `generousPassingTime`. Subsequent reads from it will return its default value.
  public mutating func clearGenerousPassingTime() {_uniqueStorage()._generousPassingTime = nil}

  public var generousDepartureTime: String {
    get {_storage._generousDepartureTime ?? String()}
    set {_uniqueStorage()._generousDepartureTime = newValue}
  }
  /// Returns true if `generousDepartureTime` has been explicitly set.
  public var hasGenerousDepartureTime: Bool {_storage._generousDepartureTime != nil}
  /// Clears the value of `generousDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearGenerousDepartureTime() {_uniqueStorage()._generousDepartureTime = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public struct Edge: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    public var edge: RouteLocation.Edge.OneOf_Edge? = nil

    public var schedule: RouteLocation.Edge.Schedule {
      get {
        if case .schedule(let v)? = edge {return v}
        return RouteLocation.Edge.Schedule()
      }
      set {edge = .schedule(newValue)}
    }

    public var association: RouteLocation.Edge.Association {
      get {
        if case .association(let v)? = edge {return v}
        return RouteLocation.Edge.Association()
      }
      set {edge = .association(newValue)}
    }

    public var unknownFields = SwiftProtobuf.UnknownStorage()

    public enum OneOf_Edge: Equatable, Sendable {
      case schedule(RouteLocation.Edge.Schedule)
      case association(RouteLocation.Edge.Association)

    }

    public struct Schedule: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var scheduleLocationComputedID: Data = Data()

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public init() {}
    }

    public struct Association: Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      public var scheduleLocationComputedID: Data = Data()

      public var associationCategory: AssociationCategory = .unknown

      public var isCancelled: Bool = false

      public var unknownFields = SwiftProtobuf.UnknownStorage()

      public init() {}
    }

    public init() {}
  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension RouteLocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "RouteLocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}next_edges\0\u{3}previous_edges\0\u{3}via_text\0\u{3}forecast_location\0\u{3}formation_loading\0\u{3}schedule_location\0\u{3}service_loading\0\u{4}\u{6}generous_arrival_time\0\u{3}generous_passing_time\0\u{3}generous_departure_time\0\u{c}\u{8}\u{5}")

  fileprivate class _StorageClass {
    var _nextEdges: [RouteLocation.Edge] = []
    var _previousEdges: [RouteLocation.Edge] = []
    var _viaText: String? = nil
    var _forecastLocation: ForecastLocation? = nil
    var _formationLoading: FormationLoading? = nil
    var _scheduleLocation: ScheduleLocation? = nil
    var _serviceLoading: ServiceLoading? = nil
    var _generousArrivalTime: String? = nil
    var _generousPassingTime: String? = nil
    var _generousDepartureTime: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _nextEdges = source._nextEdges
      _previousEdges = source._previousEdges
      _viaText = source._viaText
      _forecastLocation = source._forecastLocation
      _formationLoading = source._formationLoading
      _scheduleLocation = source._scheduleLocation
      _serviceLoading = source._serviceLoading
      _generousArrivalTime = source._generousArrivalTime
      _generousPassingTime = source._generousPassingTime
      _generousDepartureTime = source._generousDepartureTime
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeRepeatedMessageField(value: &_storage._nextEdges) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._previousEdges) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._viaText) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._forecastLocation) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._formationLoading) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._scheduleLocation) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._serviceLoading) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._generousArrivalTime) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._generousPassingTime) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._generousDepartureTime) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._nextEdges.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._nextEdges, fieldNumber: 1)
      }
      if !_storage._previousEdges.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._previousEdges, fieldNumber: 2)
      }
      try { if let v = _storage._viaText {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._forecastLocation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._formationLoading {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._scheduleLocation {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._serviceLoading {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._generousArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._generousPassingTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._generousDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RouteLocation, rhs: RouteLocation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._nextEdges != rhs_storage._nextEdges {return false}
        if _storage._previousEdges != rhs_storage._previousEdges {return false}
        if _storage._viaText != rhs_storage._viaText {return false}
        if _storage._forecastLocation != rhs_storage._forecastLocation {return false}
        if _storage._formationLoading != rhs_storage._formationLoading {return false}
        if _storage._scheduleLocation != rhs_storage._scheduleLocation {return false}
        if _storage._serviceLoading != rhs_storage._serviceLoading {return false}
        if _storage._generousArrivalTime != rhs_storage._generousArrivalTime {return false}
        if _storage._generousPassingTime != rhs_storage._generousPassingTime {return false}
        if _storage._generousDepartureTime != rhs_storage._generousDepartureTime {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RouteLocation.Edge: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = RouteLocation.protoMessageName + ".Edge"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}schedule\0\u{1}association\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: RouteLocation.Edge.Schedule?
        var hadOneofValue = false
        if let current = self.edge {
          hadOneofValue = true
          if case .schedule(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.edge = .schedule(v)
        }
      }()
      case 2: try {
        var v: RouteLocation.Edge.Association?
        var hadOneofValue = false
        if let current = self.edge {
          hadOneofValue = true
          if case .association(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.edge = .association(v)
        }
      }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.edge {
    case .schedule?: try {
      guard case .schedule(let v)? = self.edge else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .association?: try {
      guard case .association(let v)? = self.edge else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RouteLocation.Edge, rhs: RouteLocation.Edge) -> Bool {
    if lhs.edge != rhs.edge {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RouteLocation.Edge.Schedule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = RouteLocation.Edge.protoMessageName + ".Schedule"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schedule_location_computed_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.scheduleLocationComputedID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.scheduleLocationComputedID.isEmpty {
      try visitor.visitSingularBytesField(value: self.scheduleLocationComputedID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RouteLocation.Edge.Schedule, rhs: RouteLocation.Edge.Schedule) -> Bool {
    if lhs.scheduleLocationComputedID != rhs.scheduleLocationComputedID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RouteLocation.Edge.Association: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = RouteLocation.Edge.protoMessageName + ".Association"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schedule_location_computed_id\0\u{3}association_category\0\u{3}is_cancelled\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBytesField(value: &self.scheduleLocationComputedID) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.associationCategory) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isCancelled) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.scheduleLocationComputedID.isEmpty {
      try visitor.visitSingularBytesField(value: self.scheduleLocationComputedID, fieldNumber: 1)
    }
    if self.associationCategory != .unknown {
      try visitor.visitSingularEnumField(value: self.associationCategory, fieldNumber: 2)
    }
    if self.isCancelled != false {
      try visitor.visitSingularBoolField(value: self.isCancelled, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RouteLocation.Edge.Association, rhs: RouteLocation.Edge.Association) -> Bool {
    if lhs.scheduleLocationComputedID != rhs.scheduleLocationComputedID {return false}
    if lhs.associationCategory != rhs.associationCategory {return false}
    if lhs.isCancelled != rhs.isCancelled {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
