// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: schedulesAtLocation.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct SchedulesAtLocationRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// TIPLOC                            
  public var locationID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// This contains some minimal information about a schedule at the location requested.
/// Designed to use very little bandwidth.
/// More (useful) data can be requested using the IDs provided.
public struct SchedulesAtLocationResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scheduleUuid: String = String()

  public var scheduleID: String = String()

  public var scheduleLocationUuid: String = String()

  /// in YYYY-MM-DD format
  public var scheduledStartDate: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension SchedulesAtLocationRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SchedulesAtLocationRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}location_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.locationID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.locationID.isEmpty {
      try visitor.visitSingularStringField(value: self.locationID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SchedulesAtLocationRequest, rhs: SchedulesAtLocationRequest) -> Bool {
    if lhs.locationID != rhs.locationID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SchedulesAtLocationResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SchedulesAtLocationResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schedule_uuid\0\u{3}schedule_id\0\u{3}schedule_location_uuid\0\u{3}scheduled_start_date\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.scheduleUuid) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.scheduleID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.scheduleLocationUuid) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.scheduledStartDate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.scheduleUuid.isEmpty {
      try visitor.visitSingularStringField(value: self.scheduleUuid, fieldNumber: 1)
    }
    if !self.scheduleID.isEmpty {
      try visitor.visitSingularStringField(value: self.scheduleID, fieldNumber: 2)
    }
    if !self.scheduleLocationUuid.isEmpty {
      try visitor.visitSingularStringField(value: self.scheduleLocationUuid, fieldNumber: 3)
    }
    if !self.scheduledStartDate.isEmpty {
      try visitor.visitSingularStringField(value: self.scheduledStartDate, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SchedulesAtLocationResponse, rhs: SchedulesAtLocationResponse) -> Bool {
    if lhs.scheduleUuid != rhs.scheduleUuid {return false}
    if lhs.scheduleID != rhs.scheduleID {return false}
    if lhs.scheduleLocationUuid != rhs.scheduleLocationUuid {return false}
    if lhs.scheduledStartDate != rhs.scheduledStartDate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
