// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: search.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// From and To times are inclusive, and may return services scheduled up to 2 hours before and after the provided times to allow for services that are running early or late to be shown in the results.
public struct SearchRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var locationID: String = String()

  public var fromTime: String = String()

  public var toTime: String = String()

  /// If true, only passenger services will be included. If false or unspecified, all services will be included.
  public var excludeNonPassengerServices: Bool = false

  /// If true, only active services will be included. If false or unspecified, all services will be included.
  public var excludeNonActiveServices: Bool = false

  /// If true, only non-chartered services will be included. If false or unspecified, all services will be included. 
  public var excludeCharteredServices: Bool = false

  /// Filters results to include locations only of types listed. If none are given, all location types will be included.
  public var filterLocationTypes: [LocationType] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

/// The details in a SearchResponse can be used in a DescribeAtRequest to get full details.
public struct SearchResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var scheduleID: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension SearchRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SearchRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}location_id\0\u{3}from_time\0\u{3}to_time\0\u{3}exclude_non_passenger_services\0\u{3}exclude_non_active_services\0\u{3}exclude_chartered_services\0\u{3}filter_location_types\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.locationID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self.fromTime) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.toTime) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self.excludeNonPassengerServices) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self.excludeNonActiveServices) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self.excludeCharteredServices) }()
      case 7: try { try decoder.decodeRepeatedEnumField(value: &self.filterLocationTypes) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.locationID.isEmpty {
      try visitor.visitSingularStringField(value: self.locationID, fieldNumber: 1)
    }
    if !self.fromTime.isEmpty {
      try visitor.visitSingularStringField(value: self.fromTime, fieldNumber: 2)
    }
    if !self.toTime.isEmpty {
      try visitor.visitSingularStringField(value: self.toTime, fieldNumber: 3)
    }
    if self.excludeNonPassengerServices != false {
      try visitor.visitSingularBoolField(value: self.excludeNonPassengerServices, fieldNumber: 4)
    }
    if self.excludeNonActiveServices != false {
      try visitor.visitSingularBoolField(value: self.excludeNonActiveServices, fieldNumber: 5)
    }
    if self.excludeCharteredServices != false {
      try visitor.visitSingularBoolField(value: self.excludeCharteredServices, fieldNumber: 6)
    }
    if !self.filterLocationTypes.isEmpty {
      try visitor.visitPackedEnumField(value: self.filterLocationTypes, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SearchRequest, rhs: SearchRequest) -> Bool {
    if lhs.locationID != rhs.locationID {return false}
    if lhs.fromTime != rhs.fromTime {return false}
    if lhs.toTime != rhs.toTime {return false}
    if lhs.excludeNonPassengerServices != rhs.excludeNonPassengerServices {return false}
    if lhs.excludeNonActiveServices != rhs.excludeNonActiveServices {return false}
    if lhs.excludeCharteredServices != rhs.excludeCharteredServices {return false}
    if lhs.filterLocationTypes != rhs.filterLocationTypes {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension SearchResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "SearchResponse"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}schedule_id\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.scheduleID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.scheduleID.isEmpty {
      try visitor.visitSingularStringField(value: self.scheduleID, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: SearchResponse, rhs: SearchResponse) -> Bool {
    if lhs.scheduleID != rhs.scheduleID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
