// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: serviceDescription.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public struct ServiceDescription: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var schedules: [Schedule] = []

  public var formations: [Formation] = []

  public var route: [RouteLocation] = []

  public var requestedScheduleLocationUuid: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct DisruptionReason: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reasonID: UInt32 = 0

  public var reasonLocationID: String {
    get {_reasonLocationID ?? String()}
    set {_reasonLocationID = newValue}
  }
  /// Returns true if `reasonLocationID` has been explicitly set.
  public var hasReasonLocationID: Bool {self._reasonLocationID != nil}
  /// Clears the value of `reasonLocationID`. Subsequent reads from it will return its default value.
  public mutating func clearReasonLocationID() {self._reasonLocationID = nil}

  /// When true, the provided reason_id is 'near to' the provided reason_location_id. 
  /// When false, the reason_id is 'at' the reason_location_id.
  public var reasonIsNearLocation: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reasonLocationID: String? = nil
}

public struct Schedule: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uuid: String {
    get {_storage._uuid}
    set {_uniqueStorage()._uuid = newValue}
  }

  public var scheduleID: String {
    get {_storage._scheduleID}
    set {_uniqueStorage()._scheduleID = newValue}
  }

  public var uid: String {
    get {_storage._uid}
    set {_uniqueStorage()._uid = newValue}
  }

  public var headcode: String {
    get {_storage._headcode}
    set {_uniqueStorage()._headcode = newValue}
  }

  public var retailServiceID: String {
    get {_storage._retailServiceID ?? String()}
    set {_uniqueStorage()._retailServiceID = newValue}
  }
  /// Returns true if `retailServiceID` has been explicitly set.
  public var hasRetailServiceID: Bool {_storage._retailServiceID != nil}
  /// Clears the value of `retailServiceID`. Subsequent reads from it will return its default value.
  public mutating func clearRetailServiceID() {_uniqueStorage()._retailServiceID = nil}

  public var tocID: String {
    get {_storage._tocID}
    set {_uniqueStorage()._tocID = newValue}
  }

  public var service: ServiceType {
    get {_storage._service}
    set {_uniqueStorage()._service = newValue}
  }

  public var category: CategoryType {
    get {_storage._category}
    set {_uniqueStorage()._category = newValue}
  }

  public var isPassengerService: Bool {
    get {_storage._isPassengerService}
    set {_uniqueStorage()._isPassengerService = newValue}
  }

  public var isActive: Bool {
    get {_storage._isActive}
    set {_uniqueStorage()._isActive = newValue}
  }

  public var isCharter: Bool {
    get {_storage._isCharter}
    set {_uniqueStorage()._isCharter = newValue}
  }

  public var isCancelled: Bool {
    get {_storage._isCancelled}
    set {_uniqueStorage()._isCancelled = newValue}
  }

  public var cancellationReason: DisruptionReason {
    get {_storage._cancellationReason ?? DisruptionReason()}
    set {_uniqueStorage()._cancellationReason = newValue}
  }
  /// Returns true if `cancellationReason` has been explicitly set.
  public var hasCancellationReason: Bool {_storage._cancellationReason != nil}
  /// Clears the value of `cancellationReason`. Subsequent reads from it will return its default value.
  public mutating func clearCancellationReason() {_uniqueStorage()._cancellationReason = nil}

  public var divertedViaLocationID: String {
    get {_storage._divertedViaLocationID ?? String()}
    set {_uniqueStorage()._divertedViaLocationID = newValue}
  }
  /// Returns true if `divertedViaLocationID` has been explicitly set.
  public var hasDivertedViaLocationID: Bool {_storage._divertedViaLocationID != nil}
  /// Clears the value of `divertedViaLocationID`. Subsequent reads from it will return its default value.
  public mutating func clearDivertedViaLocationID() {_uniqueStorage()._divertedViaLocationID = nil}

  public var diversionReason: DisruptionReason {
    get {_storage._diversionReason ?? DisruptionReason()}
    set {_uniqueStorage()._diversionReason = newValue}
  }
  /// Returns true if `diversionReason` has been explicitly set.
  public var hasDiversionReason: Bool {_storage._diversionReason != nil}
  /// Clears the value of `diversionReason`. Subsequent reads from it will return its default value.
  public mutating func clearDiversionReason() {_uniqueStorage()._diversionReason = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

public struct Formation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct RouteLocation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var nextScheduleLocationUuids: [String] = []

  public var previousScheduleLocationUuids: [String] = []

  public var scheduleLocation: ScheduleLocation {
    get {_scheduleLocation ?? ScheduleLocation()}
    set {_scheduleLocation = newValue}
  }
  /// Returns true if `scheduleLocation` has been explicitly set.
  public var hasScheduleLocation: Bool {self._scheduleLocation != nil}
  /// Clears the value of `scheduleLocation`. Subsequent reads from it will return its default value.
  public mutating func clearScheduleLocation() {self._scheduleLocation = nil}

  public var generousArrivalTime: String {
    get {_generousArrivalTime ?? String()}
    set {_generousArrivalTime = newValue}
  }
  /// Returns true if `generousArrivalTime` has been explicitly set.
  public var hasGenerousArrivalTime: Bool {self._generousArrivalTime != nil}
  /// Clears the value of `generousArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearGenerousArrivalTime() {self._generousArrivalTime = nil}

  public var generousPassingTime: String {
    get {_generousPassingTime ?? String()}
    set {_generousPassingTime = newValue}
  }
  /// Returns true if `generousPassingTime` has been explicitly set.
  public var hasGenerousPassingTime: Bool {self._generousPassingTime != nil}
  /// Clears the value of `generousPassingTime`. Subsequent reads from it will return its default value.
  public mutating func clearGenerousPassingTime() {self._generousPassingTime = nil}

  public var generousDepartureTime: String {
    get {_generousDepartureTime ?? String()}
    set {_generousDepartureTime = newValue}
  }
  /// Returns true if `generousDepartureTime` has been explicitly set.
  public var hasGenerousDepartureTime: Bool {self._generousDepartureTime != nil}
  /// Clears the value of `generousDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearGenerousDepartureTime() {self._generousDepartureTime = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _scheduleLocation: ScheduleLocation? = nil
  fileprivate var _generousArrivalTime: String? = nil
  fileprivate var _generousPassingTime: String? = nil
  fileprivate var _generousDepartureTime: String? = nil
}

/// 'Working' times are used internally by staff
/// 'Public' times are used for display to passengers
/// Working and Public timetables may differ, typically to allow services to experience very minor (30 to 60s) delays without appearing late to the public.
/// There is no scheduled_public_passing_time because locations through which a service passes without stopping do not need to display any times to the public.
public struct ScheduleLocation: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var uuid: String {
    get {_storage._uuid}
    set {_uniqueStorage()._uuid = newValue}
  }

  public var scheduleUuid: String {
    get {_storage._scheduleUuid}
    set {_uniqueStorage()._scheduleUuid = newValue}
  }

  public var scheduleOrder: UInt32 {
    get {_storage._scheduleOrder}
    set {_uniqueStorage()._scheduleOrder = newValue}
  }

  public var locationID: String {
    get {_storage._locationID}
    set {_uniqueStorage()._locationID = newValue}
  }

  public var activities: [ActivityType] {
    get {_storage._activities}
    set {_uniqueStorage()._activities = newValue}
  }

  public var plannedActivities: [ActivityType] {
    get {_storage._plannedActivities}
    set {_uniqueStorage()._plannedActivities = newValue}
  }

  public var formationID: String {
    get {_storage._formationID ?? String()}
    set {_uniqueStorage()._formationID = newValue}
  }
  /// Returns true if `formationID` has been explicitly set.
  public var hasFormationID: Bool {_storage._formationID != nil}
  /// Clears the value of `formationID`. Subsequent reads from it will return its default value.
  public mutating func clearFormationID() {_uniqueStorage()._formationID = nil}

  public var isAffectedByDiversion: Bool {
    get {_storage._isAffectedByDiversion}
    set {_uniqueStorage()._isAffectedByDiversion = newValue}
  }

  public var type: LocationType {
    get {_storage._type}
    set {_uniqueStorage()._type = newValue}
  }

  public var workingArrivalTime: String {
    get {_storage._workingArrivalTime ?? String()}
    set {_uniqueStorage()._workingArrivalTime = newValue}
  }
  /// Returns true if `workingArrivalTime` has been explicitly set.
  public var hasWorkingArrivalTime: Bool {_storage._workingArrivalTime != nil}
  /// Clears the value of `workingArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearWorkingArrivalTime() {_uniqueStorage()._workingArrivalTime = nil}

  public var workingPassingTime: String {
    get {_storage._workingPassingTime ?? String()}
    set {_uniqueStorage()._workingPassingTime = newValue}
  }
  /// Returns true if `workingPassingTime` has been explicitly set.
  public var hasWorkingPassingTime: Bool {_storage._workingPassingTime != nil}
  /// Clears the value of `workingPassingTime`. Subsequent reads from it will return its default value.
  public mutating func clearWorkingPassingTime() {_uniqueStorage()._workingPassingTime = nil}

  public var workingDepartureTime: String {
    get {_storage._workingDepartureTime ?? String()}
    set {_uniqueStorage()._workingDepartureTime = newValue}
  }
  /// Returns true if `workingDepartureTime` has been explicitly set.
  public var hasWorkingDepartureTime: Bool {_storage._workingDepartureTime != nil}
  /// Clears the value of `workingDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearWorkingDepartureTime() {_uniqueStorage()._workingDepartureTime = nil}

  public var publicArrivalTime: String {
    get {_storage._publicArrivalTime ?? String()}
    set {_uniqueStorage()._publicArrivalTime = newValue}
  }
  /// Returns true if `publicArrivalTime` has been explicitly set.
  public var hasPublicArrivalTime: Bool {_storage._publicArrivalTime != nil}
  /// Clears the value of `publicArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearPublicArrivalTime() {_uniqueStorage()._publicArrivalTime = nil}

  public var publicDepartureTime: String {
    get {_storage._publicDepartureTime ?? String()}
    set {_uniqueStorage()._publicDepartureTime = newValue}
  }
  /// Returns true if `publicDepartureTime` has been explicitly set.
  public var hasPublicDepartureTime: Bool {_storage._publicDepartureTime != nil}
  /// Clears the value of `publicDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearPublicDepartureTime() {_uniqueStorage()._publicDepartureTime = nil}

  /// in minutes
  public var routingDelay: UInt32 {
    get {_storage._routingDelay}
    set {_uniqueStorage()._routingDelay = newValue}
  }

  public var falseDestinationLocationID: String {
    get {_storage._falseDestinationLocationID ?? String()}
    set {_uniqueStorage()._falseDestinationLocationID = newValue}
  }
  /// Returns true if `falseDestinationLocationID` has been explicitly set.
  public var hasFalseDestinationLocationID: Bool {_storage._falseDestinationLocationID != nil}
  /// Clears the value of `falseDestinationLocationID`. Subsequent reads from it will return its default value.
  public mutating func clearFalseDestinationLocationID() {_uniqueStorage()._falseDestinationLocationID = nil}

  public var isCancelled: Bool {
    get {_storage._isCancelled}
    set {_uniqueStorage()._isCancelled = newValue}
  }

  public var locationCancellationReason: DisruptionReason {
    get {_storage._locationCancellationReason ?? DisruptionReason()}
    set {_uniqueStorage()._locationCancellationReason = newValue}
  }
  /// Returns true if `locationCancellationReason` has been explicitly set.
  public var hasLocationCancellationReason: Bool {_storage._locationCancellationReason != nil}
  /// Clears the value of `locationCancellationReason`. Subsequent reads from it will return its default value.
  public mutating func clearLocationCancellationReason() {_uniqueStorage()._locationCancellationReason = nil}

  public var timetabledPlatform: String {
    get {_storage._timetabledPlatform ?? String()}
    set {_uniqueStorage()._timetabledPlatform = newValue}
  }
  /// Returns true if `timetabledPlatform` has been explicitly set.
  public var hasTimetabledPlatform: Bool {_storage._timetabledPlatform != nil}
  /// Clears the value of `timetabledPlatform`. Subsequent reads from it will return its default value.
  public mutating func clearTimetabledPlatform() {_uniqueStorage()._timetabledPlatform = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// estimated_public_*_time and estimated_working_*_time are Darwin's estimations of the most likely times.
/// estimated_minimum_*_time is Darwin's estimation of the first possible times.
/// actual_*_time are time reports from the physical train
public struct Forecast: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var isReverseFormation: Bool {
    get {_storage._isReverseFormation}
    set {_uniqueStorage()._isReverseFormation = newValue}
  }

  public var scheduleLateReason: DisruptionReason {
    get {_storage._scheduleLateReason ?? DisruptionReason()}
    set {_uniqueStorage()._scheduleLateReason = newValue}
  }
  /// Returns true if `scheduleLateReason` has been explicitly set.
  public var hasScheduleLateReason: Bool {_storage._scheduleLateReason != nil}
  /// Clears the value of `scheduleLateReason`. Subsequent reads from it will return its default value.
  public mutating func clearScheduleLateReason() {_uniqueStorage()._scheduleLateReason = nil}

  public var estimatedPublicArrivalTime: String {
    get {_storage._estimatedPublicArrivalTime ?? String()}
    set {_uniqueStorage()._estimatedPublicArrivalTime = newValue}
  }
  /// Returns true if `estimatedPublicArrivalTime` has been explicitly set.
  public var hasEstimatedPublicArrivalTime: Bool {_storage._estimatedPublicArrivalTime != nil}
  /// Clears the value of `estimatedPublicArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedPublicArrivalTime() {_uniqueStorage()._estimatedPublicArrivalTime = nil}

  public var estimatedWorkingArrivalTime: String {
    get {_storage._estimatedWorkingArrivalTime ?? String()}
    set {_uniqueStorage()._estimatedWorkingArrivalTime = newValue}
  }
  /// Returns true if `estimatedWorkingArrivalTime` has been explicitly set.
  public var hasEstimatedWorkingArrivalTime: Bool {_storage._estimatedWorkingArrivalTime != nil}
  /// Clears the value of `estimatedWorkingArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedWorkingArrivalTime() {_uniqueStorage()._estimatedWorkingArrivalTime = nil}

  public var estimatedMinimumArrivalTime: String {
    get {_storage._estimatedMinimumArrivalTime ?? String()}
    set {_uniqueStorage()._estimatedMinimumArrivalTime = newValue}
  }
  /// Returns true if `estimatedMinimumArrivalTime` has been explicitly set.
  public var hasEstimatedMinimumArrivalTime: Bool {_storage._estimatedMinimumArrivalTime != nil}
  /// Clears the value of `estimatedMinimumArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedMinimumArrivalTime() {_uniqueStorage()._estimatedMinimumArrivalTime = nil}

  public var arrivalIsDelayed: Bool {
    get {_storage._arrivalIsDelayed ?? false}
    set {_uniqueStorage()._arrivalIsDelayed = newValue}
  }
  /// Returns true if `arrivalIsDelayed` has been explicitly set.
  public var hasArrivalIsDelayed: Bool {_storage._arrivalIsDelayed != nil}
  /// Clears the value of `arrivalIsDelayed`. Subsequent reads from it will return its default value.
  public mutating func clearArrivalIsDelayed() {_uniqueStorage()._arrivalIsDelayed = nil}

  public var arrivalIsDelayedByUnknownAmount: Bool {
    get {_storage._arrivalIsDelayedByUnknownAmount ?? false}
    set {_uniqueStorage()._arrivalIsDelayedByUnknownAmount = newValue}
  }
  /// Returns true if `arrivalIsDelayedByUnknownAmount` has been explicitly set.
  public var hasArrivalIsDelayedByUnknownAmount: Bool {_storage._arrivalIsDelayedByUnknownAmount != nil}
  /// Clears the value of `arrivalIsDelayedByUnknownAmount`. Subsequent reads from it will return its default value.
  public mutating func clearArrivalIsDelayedByUnknownAmount() {_uniqueStorage()._arrivalIsDelayedByUnknownAmount = nil}

  public var estimatedPassingTime: String {
    get {_storage._estimatedPassingTime ?? String()}
    set {_uniqueStorage()._estimatedPassingTime = newValue}
  }
  /// Returns true if `estimatedPassingTime` has been explicitly set.
  public var hasEstimatedPassingTime: Bool {_storage._estimatedPassingTime != nil}
  /// Clears the value of `estimatedPassingTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedPassingTime() {_uniqueStorage()._estimatedPassingTime = nil}

  public var estimatedMinimumPassingTime: String {
    get {_storage._estimatedMinimumPassingTime ?? String()}
    set {_uniqueStorage()._estimatedMinimumPassingTime = newValue}
  }
  /// Returns true if `estimatedMinimumPassingTime` has been explicitly set.
  public var hasEstimatedMinimumPassingTime: Bool {_storage._estimatedMinimumPassingTime != nil}
  /// Clears the value of `estimatedMinimumPassingTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedMinimumPassingTime() {_uniqueStorage()._estimatedMinimumPassingTime = nil}

  public var passingIsDelayed: Bool {
    get {_storage._passingIsDelayed ?? false}
    set {_uniqueStorage()._passingIsDelayed = newValue}
  }
  /// Returns true if `passingIsDelayed` has been explicitly set.
  public var hasPassingIsDelayed: Bool {_storage._passingIsDelayed != nil}
  /// Clears the value of `passingIsDelayed`. Subsequent reads from it will return its default value.
  public mutating func clearPassingIsDelayed() {_uniqueStorage()._passingIsDelayed = nil}

  public var passingIsDelayedByUnknownAmount: Bool {
    get {_storage._passingIsDelayedByUnknownAmount ?? false}
    set {_uniqueStorage()._passingIsDelayedByUnknownAmount = newValue}
  }
  /// Returns true if `passingIsDelayedByUnknownAmount` has been explicitly set.
  public var hasPassingIsDelayedByUnknownAmount: Bool {_storage._passingIsDelayedByUnknownAmount != nil}
  /// Clears the value of `passingIsDelayedByUnknownAmount`. Subsequent reads from it will return its default value.
  public mutating func clearPassingIsDelayedByUnknownAmount() {_uniqueStorage()._passingIsDelayedByUnknownAmount = nil}

  public var estimatedPublicDepartureTime: String {
    get {_storage._estimatedPublicDepartureTime ?? String()}
    set {_uniqueStorage()._estimatedPublicDepartureTime = newValue}
  }
  /// Returns true if `estimatedPublicDepartureTime` has been explicitly set.
  public var hasEstimatedPublicDepartureTime: Bool {_storage._estimatedPublicDepartureTime != nil}
  /// Clears the value of `estimatedPublicDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedPublicDepartureTime() {_uniqueStorage()._estimatedPublicDepartureTime = nil}

  public var estimatedWorkingDepartureTime: String {
    get {_storage._estimatedWorkingDepartureTime ?? String()}
    set {_uniqueStorage()._estimatedWorkingDepartureTime = newValue}
  }
  /// Returns true if `estimatedWorkingDepartureTime` has been explicitly set.
  public var hasEstimatedWorkingDepartureTime: Bool {_storage._estimatedWorkingDepartureTime != nil}
  /// Clears the value of `estimatedWorkingDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedWorkingDepartureTime() {_uniqueStorage()._estimatedWorkingDepartureTime = nil}

  public var estimatedMinimumDepartureTime: String {
    get {_storage._estimatedMinimumDepartureTime ?? String()}
    set {_uniqueStorage()._estimatedMinimumDepartureTime = newValue}
  }
  /// Returns true if `estimatedMinimumDepartureTime` has been explicitly set.
  public var hasEstimatedMinimumDepartureTime: Bool {_storage._estimatedMinimumDepartureTime != nil}
  /// Clears the value of `estimatedMinimumDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearEstimatedMinimumDepartureTime() {_uniqueStorage()._estimatedMinimumDepartureTime = nil}

  public var departureIsDelayed: Bool {
    get {_storage._departureIsDelayed ?? false}
    set {_uniqueStorage()._departureIsDelayed = newValue}
  }
  /// Returns true if `departureIsDelayed` has been explicitly set.
  public var hasDepartureIsDelayed: Bool {_storage._departureIsDelayed != nil}
  /// Clears the value of `departureIsDelayed`. Subsequent reads from it will return its default value.
  public mutating func clearDepartureIsDelayed() {_uniqueStorage()._departureIsDelayed = nil}

  public var departureIsDelayedByUnknownAmount: Bool {
    get {_storage._departureIsDelayedByUnknownAmount ?? false}
    set {_uniqueStorage()._departureIsDelayedByUnknownAmount = newValue}
  }
  /// Returns true if `departureIsDelayedByUnknownAmount` has been explicitly set.
  public var hasDepartureIsDelayedByUnknownAmount: Bool {_storage._departureIsDelayedByUnknownAmount != nil}
  /// Clears the value of `departureIsDelayedByUnknownAmount`. Subsequent reads from it will return its default value.
  public mutating func clearDepartureIsDelayedByUnknownAmount() {_uniqueStorage()._departureIsDelayedByUnknownAmount = nil}

  public var actualArrivalTime: String {
    get {_storage._actualArrivalTime ?? String()}
    set {_uniqueStorage()._actualArrivalTime = newValue}
  }
  /// Returns true if `actualArrivalTime` has been explicitly set.
  public var hasActualArrivalTime: Bool {_storage._actualArrivalTime != nil}
  /// Clears the value of `actualArrivalTime`. Subsequent reads from it will return its default value.
  public mutating func clearActualArrivalTime() {_uniqueStorage()._actualArrivalTime = nil}

  public var actualArrivalDataClass: String {
    get {_storage._actualArrivalDataClass ?? String()}
    set {_uniqueStorage()._actualArrivalDataClass = newValue}
  }
  /// Returns true if `actualArrivalDataClass` has been explicitly set.
  public var hasActualArrivalDataClass: Bool {_storage._actualArrivalDataClass != nil}
  /// Clears the value of `actualArrivalDataClass`. Subsequent reads from it will return its default value.
  public mutating func clearActualArrivalDataClass() {_uniqueStorage()._actualArrivalDataClass = nil}

  public var actualArrivalDataSource: String {
    get {_storage._actualArrivalDataSource ?? String()}
    set {_uniqueStorage()._actualArrivalDataSource = newValue}
  }
  /// Returns true if `actualArrivalDataSource` has been explicitly set.
  public var hasActualArrivalDataSource: Bool {_storage._actualArrivalDataSource != nil}
  /// Clears the value of `actualArrivalDataSource`. Subsequent reads from it will return its default value.
  public mutating func clearActualArrivalDataSource() {_uniqueStorage()._actualArrivalDataSource = nil}

  public var actualArrivalDataSourceSystem: String {
    get {_storage._actualArrivalDataSourceSystem ?? String()}
    set {_uniqueStorage()._actualArrivalDataSourceSystem = newValue}
  }
  /// Returns true if `actualArrivalDataSourceSystem` has been explicitly set.
  public var hasActualArrivalDataSourceSystem: Bool {_storage._actualArrivalDataSourceSystem != nil}
  /// Clears the value of `actualArrivalDataSourceSystem`. Subsequent reads from it will return its default value.
  public mutating func clearActualArrivalDataSourceSystem() {_uniqueStorage()._actualArrivalDataSourceSystem = nil}

  public var actualPassingTime: String {
    get {_storage._actualPassingTime ?? String()}
    set {_uniqueStorage()._actualPassingTime = newValue}
  }
  /// Returns true if `actualPassingTime` has been explicitly set.
  public var hasActualPassingTime: Bool {_storage._actualPassingTime != nil}
  /// Clears the value of `actualPassingTime`. Subsequent reads from it will return its default value.
  public mutating func clearActualPassingTime() {_uniqueStorage()._actualPassingTime = nil}

  public var actualPassingDataClass: String {
    get {_storage._actualPassingDataClass ?? String()}
    set {_uniqueStorage()._actualPassingDataClass = newValue}
  }
  /// Returns true if `actualPassingDataClass` has been explicitly set.
  public var hasActualPassingDataClass: Bool {_storage._actualPassingDataClass != nil}
  /// Clears the value of `actualPassingDataClass`. Subsequent reads from it will return its default value.
  public mutating func clearActualPassingDataClass() {_uniqueStorage()._actualPassingDataClass = nil}

  public var actualPassingDataSource: String {
    get {_storage._actualPassingDataSource ?? String()}
    set {_uniqueStorage()._actualPassingDataSource = newValue}
  }
  /// Returns true if `actualPassingDataSource` has been explicitly set.
  public var hasActualPassingDataSource: Bool {_storage._actualPassingDataSource != nil}
  /// Clears the value of `actualPassingDataSource`. Subsequent reads from it will return its default value.
  public mutating func clearActualPassingDataSource() {_uniqueStorage()._actualPassingDataSource = nil}

  public var actualPassingDataSourceSystem: String {
    get {_storage._actualPassingDataSourceSystem ?? String()}
    set {_uniqueStorage()._actualPassingDataSourceSystem = newValue}
  }
  /// Returns true if `actualPassingDataSourceSystem` has been explicitly set.
  public var hasActualPassingDataSourceSystem: Bool {_storage._actualPassingDataSourceSystem != nil}
  /// Clears the value of `actualPassingDataSourceSystem`. Subsequent reads from it will return its default value.
  public mutating func clearActualPassingDataSourceSystem() {_uniqueStorage()._actualPassingDataSourceSystem = nil}

  public var actualDepartureTime: String {
    get {_storage._actualDepartureTime ?? String()}
    set {_uniqueStorage()._actualDepartureTime = newValue}
  }
  /// Returns true if `actualDepartureTime` has been explicitly set.
  public var hasActualDepartureTime: Bool {_storage._actualDepartureTime != nil}
  /// Clears the value of `actualDepartureTime`. Subsequent reads from it will return its default value.
  public mutating func clearActualDepartureTime() {_uniqueStorage()._actualDepartureTime = nil}

  public var actualDepartureDataClass: String {
    get {_storage._actualDepartureDataClass ?? String()}
    set {_uniqueStorage()._actualDepartureDataClass = newValue}
  }
  /// Returns true if `actualDepartureDataClass` has been explicitly set.
  public var hasActualDepartureDataClass: Bool {_storage._actualDepartureDataClass != nil}
  /// Clears the value of `actualDepartureDataClass`. Subsequent reads from it will return its default value.
  public mutating func clearActualDepartureDataClass() {_uniqueStorage()._actualDepartureDataClass = nil}

  public var actualDepartureDataSource: String {
    get {_storage._actualDepartureDataSource ?? String()}
    set {_uniqueStorage()._actualDepartureDataSource = newValue}
  }
  /// Returns true if `actualDepartureDataSource` has been explicitly set.
  public var hasActualDepartureDataSource: Bool {_storage._actualDepartureDataSource != nil}
  /// Clears the value of `actualDepartureDataSource`. Subsequent reads from it will return its default value.
  public mutating func clearActualDepartureDataSource() {_uniqueStorage()._actualDepartureDataSource = nil}

  public var actualDepartureDataSourceSystem: String {
    get {_storage._actualDepartureDataSourceSystem ?? String()}
    set {_uniqueStorage()._actualDepartureDataSourceSystem = newValue}
  }
  /// Returns true if `actualDepartureDataSourceSystem` has been explicitly set.
  public var hasActualDepartureDataSourceSystem: Bool {_storage._actualDepartureDataSourceSystem != nil}
  /// Clears the value of `actualDepartureDataSourceSystem`. Subsequent reads from it will return its default value.
  public mutating func clearActualDepartureDataSourceSystem() {_uniqueStorage()._actualDepartureDataSourceSystem = nil}

  public var locationLateReason: DisruptionReason {
    get {_storage._locationLateReason ?? DisruptionReason()}
    set {_uniqueStorage()._locationLateReason = newValue}
  }
  /// Returns true if `locationLateReason` has been explicitly set.
  public var hasLocationLateReason: Bool {_storage._locationLateReason != nil}
  /// Clears the value of `locationLateReason`. Subsequent reads from it will return its default value.
  public mutating func clearLocationLateReason() {_uniqueStorage()._locationLateReason = nil}

  public var locationDisruptionRisk: String {
    get {_storage._locationDisruptionRisk ?? String()}
    set {_uniqueStorage()._locationDisruptionRisk = newValue}
  }
  /// Returns true if `locationDisruptionRisk` has been explicitly set.
  public var hasLocationDisruptionRisk: Bool {_storage._locationDisruptionRisk != nil}
  /// Clears the value of `locationDisruptionRisk`. Subsequent reads from it will return its default value.
  public mutating func clearLocationDisruptionRisk() {_uniqueStorage()._locationDisruptionRisk = nil}

  public var locationDisruptionRiskReason: DisruptionReason {
    get {_storage._locationDisruptionRiskReason ?? DisruptionReason()}
    set {_uniqueStorage()._locationDisruptionRiskReason = newValue}
  }
  /// Returns true if `locationDisruptionRiskReason` has been explicitly set.
  public var hasLocationDisruptionRiskReason: Bool {_storage._locationDisruptionRiskReason != nil}
  /// Clears the value of `locationDisruptionRiskReason`. Subsequent reads from it will return its default value.
  public mutating func clearLocationDisruptionRiskReason() {_uniqueStorage()._locationDisruptionRiskReason = nil}

  public var affectedBy: String {
    get {_storage._affectedBy ?? String()}
    set {_uniqueStorage()._affectedBy = newValue}
  }
  /// Returns true if `affectedBy` has been explicitly set.
  public var hasAffectedBy: Bool {_storage._affectedBy != nil}
  /// Clears the value of `affectedBy`. Subsequent reads from it will return its default value.
  public mutating func clearAffectedBy() {_uniqueStorage()._affectedBy = nil}

  /// do not display platform information if true
  public var platformIsSuppressed: Bool {
    get {_storage._platformIsSuppressed ?? false}
    set {_uniqueStorage()._platformIsSuppressed = newValue}
  }
  /// Returns true if `platformIsSuppressed` has been explicitly set.
  public var hasPlatformIsSuppressed: Bool {_storage._platformIsSuppressed != nil}
  /// Clears the value of `platformIsSuppressed`. Subsequent reads from it will return its default value.
  public mutating func clearPlatformIsSuppressed() {_uniqueStorage()._platformIsSuppressed = nil}

  public var platformIsSuppressedByCis: Bool {
    get {_storage._platformIsSuppressedByCis ?? false}
    set {_uniqueStorage()._platformIsSuppressedByCis = newValue}
  }
  /// Returns true if `platformIsSuppressedByCis` has been explicitly set.
  public var hasPlatformIsSuppressedByCis: Bool {_storage._platformIsSuppressedByCis != nil}
  /// Clears the value of `platformIsSuppressedByCis`. Subsequent reads from it will return its default value.
  public mutating func clearPlatformIsSuppressedByCis() {_uniqueStorage()._platformIsSuppressedByCis = nil}

  public var platformDataSource: Forecast.PlatformDataSource {
    get {_storage._platformDataSource ?? .platformUnknown}
    set {_uniqueStorage()._platformDataSource = newValue}
  }
  /// Returns true if `platformDataSource` has been explicitly set.
  public var hasPlatformDataSource: Bool {_storage._platformDataSource != nil}
  /// Clears the value of `platformDataSource`. Subsequent reads from it will return its default value.
  public mutating func clearPlatformDataSource() {_uniqueStorage()._platformDataSource = nil}

  public var platformIsConfirmed: Bool {
    get {_storage._platformIsConfirmed ?? false}
    set {_uniqueStorage()._platformIsConfirmed = newValue}
  }
  /// Returns true if `platformIsConfirmed` has been explicitly set.
  public var hasPlatformIsConfirmed: Bool {_storage._platformIsConfirmed != nil}
  /// Clears the value of `platformIsConfirmed`. Subsequent reads from it will return its default value.
  public mutating func clearPlatformIsConfirmed() {_uniqueStorage()._platformIsConfirmed = nil}

  public var serviceIsSuppressed: Bool {
    get {_storage._serviceIsSuppressed}
    set {_uniqueStorage()._serviceIsSuppressed = newValue}
  }

  public var serviceDetatchesFromFront: Bool {
    get {_storage._serviceDetatchesFromFront}
    set {_uniqueStorage()._serviceDetatchesFromFront = newValue}
  }

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public enum PlatformDataSource: SwiftProtobuf.Enum, Swift.CaseIterable {
    public typealias RawValue = Int
    case platformUnknown // = 0
    case platformPlanned // = 1
    case platformAutomatic // = 2
    case platformManual // = 3
    case UNRECOGNIZED(Int)

    public init() {
      self = .platformUnknown
    }

    public init?(rawValue: Int) {
      switch rawValue {
      case 0: self = .platformUnknown
      case 1: self = .platformPlanned
      case 2: self = .platformAutomatic
      case 3: self = .platformManual
      default: self = .UNRECOGNIZED(rawValue)
      }
    }

    public var rawValue: Int {
      switch self {
      case .platformUnknown: return 0
      case .platformPlanned: return 1
      case .platformAutomatic: return 2
      case .platformManual: return 3
      case .UNRECOGNIZED(let i): return i
      }
    }

    // The compiler won't synthesize support with the UNRECOGNIZED case.
    public static let allCases: [Forecast.PlatformDataSource] = [
      .platformUnknown,
      .platformPlanned,
      .platformAutomatic,
      .platformManual,
    ]

  }

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

extension ServiceDescription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ServiceDescription"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}schedules\0\u{1}formations\0\u{1}route\0\u{3}requested_schedule_location_uuid\0\u{c}\u{5}\u{b}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.schedules) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.formations) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.route) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.requestedScheduleLocationUuid) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.schedules.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.schedules, fieldNumber: 1)
    }
    if !self.formations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.formations, fieldNumber: 2)
    }
    if !self.route.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.route, fieldNumber: 3)
    }
    if !self.requestedScheduleLocationUuid.isEmpty {
      try visitor.visitSingularStringField(value: self.requestedScheduleLocationUuid, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ServiceDescription, rhs: ServiceDescription) -> Bool {
    if lhs.schedules != rhs.schedules {return false}
    if lhs.formations != rhs.formations {return false}
    if lhs.route != rhs.route {return false}
    if lhs.requestedScheduleLocationUuid != rhs.requestedScheduleLocationUuid {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension DisruptionReason: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "DisruptionReason"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}reason_id\0\u{3}reason_location_id\0\u{3}reason_is_near_location\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.reasonID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._reasonLocationID) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.reasonIsNearLocation) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.reasonID != 0 {
      try visitor.visitSingularUInt32Field(value: self.reasonID, fieldNumber: 1)
    }
    try { if let v = self._reasonLocationID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    if self.reasonIsNearLocation != false {
      try visitor.visitSingularBoolField(value: self.reasonIsNearLocation, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: DisruptionReason, rhs: DisruptionReason) -> Bool {
    if lhs.reasonID != rhs.reasonID {return false}
    if lhs._reasonLocationID != rhs._reasonLocationID {return false}
    if lhs.reasonIsNearLocation != rhs.reasonIsNearLocation {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Schedule: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "Schedule"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uuid\0\u{4}\u{3}schedule_id\0\u{1}uid\0\u{2}\u{3}headcode\0\u{3}retail_service_id\0\u{3}toc_id\0\u{1}service\0\u{1}category\0\u{3}is_passenger_service\0\u{3}is_active\0\u{4}\u{2}is_charter\0\u{3}is_cancelled\0\u{3}cancellation_reason\0\u{3}diverted_via_location_id\0\u{3}diversion_reason\0\u{c}\u{2}\u{2}\u{c}\u{6}\u{2}\u{c}\u{f}\u{1}")

  fileprivate class _StorageClass {
    var _uuid: String = String()
    var _scheduleID: String = String()
    var _uid: String = String()
    var _headcode: String = String()
    var _retailServiceID: String? = nil
    var _tocID: String = String()
    var _service: ServiceType = .serviceUnknown
    var _category: CategoryType = .categoryUnknown
    var _isPassengerService: Bool = false
    var _isActive: Bool = false
    var _isCharter: Bool = false
    var _isCancelled: Bool = false
    var _cancellationReason: DisruptionReason? = nil
    var _divertedViaLocationID: String? = nil
    var _diversionReason: DisruptionReason? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _uuid = source._uuid
      _scheduleID = source._scheduleID
      _uid = source._uid
      _headcode = source._headcode
      _retailServiceID = source._retailServiceID
      _tocID = source._tocID
      _service = source._service
      _category = source._category
      _isPassengerService = source._isPassengerService
      _isActive = source._isActive
      _isCharter = source._isCharter
      _isCancelled = source._isCancelled
      _cancellationReason = source._cancellationReason
      _divertedViaLocationID = source._divertedViaLocationID
      _diversionReason = source._diversionReason
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._uuid) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._scheduleID) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._uid) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._headcode) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._retailServiceID) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._tocID) }()
        case 11: try { try decoder.decodeSingularEnumField(value: &_storage._service) }()
        case 12: try { try decoder.decodeSingularEnumField(value: &_storage._category) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._isPassengerService) }()
        case 14: try { try decoder.decodeSingularBoolField(value: &_storage._isActive) }()
        case 16: try { try decoder.decodeSingularBoolField(value: &_storage._isCharter) }()
        case 17: try { try decoder.decodeSingularBoolField(value: &_storage._isCancelled) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._cancellationReason) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._divertedViaLocationID) }()
        case 20: try { try decoder.decodeSingularMessageField(value: &_storage._diversionReason) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._uuid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uuid, fieldNumber: 1)
      }
      if !_storage._scheduleID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scheduleID, fieldNumber: 4)
      }
      if !_storage._uid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uid, fieldNumber: 5)
      }
      if !_storage._headcode.isEmpty {
        try visitor.visitSingularStringField(value: _storage._headcode, fieldNumber: 8)
      }
      try { if let v = _storage._retailServiceID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      if !_storage._tocID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._tocID, fieldNumber: 10)
      }
      if _storage._service != .serviceUnknown {
        try visitor.visitSingularEnumField(value: _storage._service, fieldNumber: 11)
      }
      if _storage._category != .categoryUnknown {
        try visitor.visitSingularEnumField(value: _storage._category, fieldNumber: 12)
      }
      if _storage._isPassengerService != false {
        try visitor.visitSingularBoolField(value: _storage._isPassengerService, fieldNumber: 13)
      }
      if _storage._isActive != false {
        try visitor.visitSingularBoolField(value: _storage._isActive, fieldNumber: 14)
      }
      if _storage._isCharter != false {
        try visitor.visitSingularBoolField(value: _storage._isCharter, fieldNumber: 16)
      }
      if _storage._isCancelled != false {
        try visitor.visitSingularBoolField(value: _storage._isCancelled, fieldNumber: 17)
      }
      try { if let v = _storage._cancellationReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._divertedViaLocationID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 19)
      } }()
      try { if let v = _storage._diversionReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 20)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Schedule, rhs: Schedule) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._uuid != rhs_storage._uuid {return false}
        if _storage._scheduleID != rhs_storage._scheduleID {return false}
        if _storage._uid != rhs_storage._uid {return false}
        if _storage._headcode != rhs_storage._headcode {return false}
        if _storage._retailServiceID != rhs_storage._retailServiceID {return false}
        if _storage._tocID != rhs_storage._tocID {return false}
        if _storage._service != rhs_storage._service {return false}
        if _storage._category != rhs_storage._category {return false}
        if _storage._isPassengerService != rhs_storage._isPassengerService {return false}
        if _storage._isActive != rhs_storage._isActive {return false}
        if _storage._isCharter != rhs_storage._isCharter {return false}
        if _storage._isCancelled != rhs_storage._isCancelled {return false}
        if _storage._cancellationReason != rhs_storage._cancellationReason {return false}
        if _storage._divertedViaLocationID != rhs_storage._divertedViaLocationID {return false}
        if _storage._diversionReason != rhs_storage._diversionReason {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Formation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "Formation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap()

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    // Load everything into unknown fields
    while try decoder.nextFieldNumber() != nil {}
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Formation, rhs: Formation) -> Bool {
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension RouteLocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "RouteLocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}next_schedule_location_uuids\0\u{3}previous_schedule_location_uuids\0\u{4}\u{3}schedule_location\0\u{4}\u{8}generous_arrival_time\0\u{3}generous_passing_time\0\u{3}generous_departure_time\0\u{c}\u{3}\u{2}\u{c}\u{6}\u{4}\u{c}\u{a}\u{3}")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedStringField(value: &self.nextScheduleLocationUuids) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.previousScheduleLocationUuids) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._scheduleLocation) }()
      case 13: try { try decoder.decodeSingularStringField(value: &self._generousArrivalTime) }()
      case 14: try { try decoder.decodeSingularStringField(value: &self._generousPassingTime) }()
      case 15: try { try decoder.decodeSingularStringField(value: &self._generousDepartureTime) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.nextScheduleLocationUuids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.nextScheduleLocationUuids, fieldNumber: 1)
    }
    if !self.previousScheduleLocationUuids.isEmpty {
      try visitor.visitRepeatedStringField(value: self.previousScheduleLocationUuids, fieldNumber: 2)
    }
    try { if let v = self._scheduleLocation {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._generousArrivalTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 13)
    } }()
    try { if let v = self._generousPassingTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 14)
    } }()
    try { if let v = self._generousDepartureTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 15)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: RouteLocation, rhs: RouteLocation) -> Bool {
    if lhs.nextScheduleLocationUuids != rhs.nextScheduleLocationUuids {return false}
    if lhs.previousScheduleLocationUuids != rhs.previousScheduleLocationUuids {return false}
    if lhs._scheduleLocation != rhs._scheduleLocation {return false}
    if lhs._generousArrivalTime != rhs._generousArrivalTime {return false}
    if lhs._generousPassingTime != rhs._generousPassingTime {return false}
    if lhs._generousDepartureTime != rhs._generousDepartureTime {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension ScheduleLocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "ScheduleLocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}uuid\0\u{3}schedule_uuid\0\u{3}schedule_order\0\u{3}location_id\0\u{1}activities\0\u{3}planned_activities\0\u{3}formation_id\0\u{3}is_affected_by_diversion\0\u{1}type\0\u{3}working_arrival_time\0\u{3}working_passing_time\0\u{3}working_departure_time\0\u{3}public_arrival_time\0\u{3}public_departure_time\0\u{3}routing_delay\0\u{3}false_destination_location_id\0\u{3}is_cancelled\0\u{3}location_cancellation_reason\0\u{3}timetabled_platform\0")

  fileprivate class _StorageClass {
    var _uuid: String = String()
    var _scheduleUuid: String = String()
    var _scheduleOrder: UInt32 = 0
    var _locationID: String = String()
    var _activities: [ActivityType] = []
    var _plannedActivities: [ActivityType] = []
    var _formationID: String? = nil
    var _isAffectedByDiversion: Bool = false
    var _type: LocationType = .locationUnknown
    var _workingArrivalTime: String? = nil
    var _workingPassingTime: String? = nil
    var _workingDepartureTime: String? = nil
    var _publicArrivalTime: String? = nil
    var _publicDepartureTime: String? = nil
    var _routingDelay: UInt32 = 0
    var _falseDestinationLocationID: String? = nil
    var _isCancelled: Bool = false
    var _locationCancellationReason: DisruptionReason? = nil
    var _timetabledPlatform: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _uuid = source._uuid
      _scheduleUuid = source._scheduleUuid
      _scheduleOrder = source._scheduleOrder
      _locationID = source._locationID
      _activities = source._activities
      _plannedActivities = source._plannedActivities
      _formationID = source._formationID
      _isAffectedByDiversion = source._isAffectedByDiversion
      _type = source._type
      _workingArrivalTime = source._workingArrivalTime
      _workingPassingTime = source._workingPassingTime
      _workingDepartureTime = source._workingDepartureTime
      _publicArrivalTime = source._publicArrivalTime
      _publicDepartureTime = source._publicDepartureTime
      _routingDelay = source._routingDelay
      _falseDestinationLocationID = source._falseDestinationLocationID
      _isCancelled = source._isCancelled
      _locationCancellationReason = source._locationCancellationReason
      _timetabledPlatform = source._timetabledPlatform
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._uuid) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._scheduleUuid) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._scheduleOrder) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._locationID) }()
        case 5: try { try decoder.decodeRepeatedEnumField(value: &_storage._activities) }()
        case 6: try { try decoder.decodeRepeatedEnumField(value: &_storage._plannedActivities) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._formationID) }()
        case 8: try { try decoder.decodeSingularBoolField(value: &_storage._isAffectedByDiversion) }()
        case 9: try { try decoder.decodeSingularEnumField(value: &_storage._type) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._workingArrivalTime) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._workingPassingTime) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._workingDepartureTime) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._publicArrivalTime) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._publicDepartureTime) }()
        case 15: try { try decoder.decodeSingularUInt32Field(value: &_storage._routingDelay) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._falseDestinationLocationID) }()
        case 17: try { try decoder.decodeSingularBoolField(value: &_storage._isCancelled) }()
        case 18: try { try decoder.decodeSingularMessageField(value: &_storage._locationCancellationReason) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._timetabledPlatform) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if !_storage._uuid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._uuid, fieldNumber: 1)
      }
      if !_storage._scheduleUuid.isEmpty {
        try visitor.visitSingularStringField(value: _storage._scheduleUuid, fieldNumber: 2)
      }
      if _storage._scheduleOrder != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._scheduleOrder, fieldNumber: 3)
      }
      if !_storage._locationID.isEmpty {
        try visitor.visitSingularStringField(value: _storage._locationID, fieldNumber: 4)
      }
      if !_storage._activities.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._activities, fieldNumber: 5)
      }
      if !_storage._plannedActivities.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._plannedActivities, fieldNumber: 6)
      }
      try { if let v = _storage._formationID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      if _storage._isAffectedByDiversion != false {
        try visitor.visitSingularBoolField(value: _storage._isAffectedByDiversion, fieldNumber: 8)
      }
      if _storage._type != .locationUnknown {
        try visitor.visitSingularEnumField(value: _storage._type, fieldNumber: 9)
      }
      try { if let v = _storage._workingArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._workingPassingTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._workingDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._publicArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._publicDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      if _storage._routingDelay != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._routingDelay, fieldNumber: 15)
      }
      try { if let v = _storage._falseDestinationLocationID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 16)
      } }()
      if _storage._isCancelled != false {
        try visitor.visitSingularBoolField(value: _storage._isCancelled, fieldNumber: 17)
      }
      try { if let v = _storage._locationCancellationReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._timetabledPlatform {
        try visitor.visitSingularStringField(value: v, fieldNumber: 19)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: ScheduleLocation, rhs: ScheduleLocation) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._uuid != rhs_storage._uuid {return false}
        if _storage._scheduleUuid != rhs_storage._scheduleUuid {return false}
        if _storage._scheduleOrder != rhs_storage._scheduleOrder {return false}
        if _storage._locationID != rhs_storage._locationID {return false}
        if _storage._activities != rhs_storage._activities {return false}
        if _storage._plannedActivities != rhs_storage._plannedActivities {return false}
        if _storage._formationID != rhs_storage._formationID {return false}
        if _storage._isAffectedByDiversion != rhs_storage._isAffectedByDiversion {return false}
        if _storage._type != rhs_storage._type {return false}
        if _storage._workingArrivalTime != rhs_storage._workingArrivalTime {return false}
        if _storage._workingPassingTime != rhs_storage._workingPassingTime {return false}
        if _storage._workingDepartureTime != rhs_storage._workingDepartureTime {return false}
        if _storage._publicArrivalTime != rhs_storage._publicArrivalTime {return false}
        if _storage._publicDepartureTime != rhs_storage._publicDepartureTime {return false}
        if _storage._routingDelay != rhs_storage._routingDelay {return false}
        if _storage._falseDestinationLocationID != rhs_storage._falseDestinationLocationID {return false}
        if _storage._isCancelled != rhs_storage._isCancelled {return false}
        if _storage._locationCancellationReason != rhs_storage._locationCancellationReason {return false}
        if _storage._timetabledPlatform != rhs_storage._timetabledPlatform {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Forecast: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = "Forecast"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}is_reverse_formation\0\u{3}schedule_late_reason\0\u{3}estimated_public_arrival_time\0\u{3}estimated_working_arrival_time\0\u{3}estimated_minimum_arrival_time\0\u{3}arrival_is_delayed\0\u{3}arrival_is_delayed_by_unknown_amount\0\u{3}estimated_passing_time\0\u{3}estimated_minimum_passing_time\0\u{3}passing_is_delayed\0\u{3}passing_is_delayed_by_unknown_amount\0\u{3}estimated_public_departure_time\0\u{3}estimated_working_departure_time\0\u{3}estimated_minimum_departure_time\0\u{3}departure_is_delayed\0\u{3}departure_is_delayed_by_unknown_amount\0\u{3}actual_arrival_time\0\u{3}actual_arrival_data_class\0\u{3}actual_arrival_data_source\0\u{3}actual_arrival_data_source_system\0\u{3}actual_passing_time\0\u{3}actual_passing_data_class\0\u{3}actual_passing_data_source\0\u{3}actual_passing_data_source_system\0\u{3}actual_departure_time\0\u{3}actual_departure_data_class\0\u{3}actual_departure_data_source\0\u{3}actual_departure_data_source_system\0\u{3}location_late_reason\0\u{3}location_disruption_risk\0\u{3}location_disruption_risk_reason\0\u{3}affected_by\0\u{3}platform_is_suppressed\0\u{3}platform_is_suppressed_by_cis\0\u{3}platform_data_source\0\u{3}platform_is_confirmed\0\u{3}service_is_suppressed\0\u{3}service_detatches_from_front\0")

  fileprivate class _StorageClass {
    var _isReverseFormation: Bool = false
    var _scheduleLateReason: DisruptionReason? = nil
    var _estimatedPublicArrivalTime: String? = nil
    var _estimatedWorkingArrivalTime: String? = nil
    var _estimatedMinimumArrivalTime: String? = nil
    var _arrivalIsDelayed: Bool? = nil
    var _arrivalIsDelayedByUnknownAmount: Bool? = nil
    var _estimatedPassingTime: String? = nil
    var _estimatedMinimumPassingTime: String? = nil
    var _passingIsDelayed: Bool? = nil
    var _passingIsDelayedByUnknownAmount: Bool? = nil
    var _estimatedPublicDepartureTime: String? = nil
    var _estimatedWorkingDepartureTime: String? = nil
    var _estimatedMinimumDepartureTime: String? = nil
    var _departureIsDelayed: Bool? = nil
    var _departureIsDelayedByUnknownAmount: Bool? = nil
    var _actualArrivalTime: String? = nil
    var _actualArrivalDataClass: String? = nil
    var _actualArrivalDataSource: String? = nil
    var _actualArrivalDataSourceSystem: String? = nil
    var _actualPassingTime: String? = nil
    var _actualPassingDataClass: String? = nil
    var _actualPassingDataSource: String? = nil
    var _actualPassingDataSourceSystem: String? = nil
    var _actualDepartureTime: String? = nil
    var _actualDepartureDataClass: String? = nil
    var _actualDepartureDataSource: String? = nil
    var _actualDepartureDataSourceSystem: String? = nil
    var _locationLateReason: DisruptionReason? = nil
    var _locationDisruptionRisk: String? = nil
    var _locationDisruptionRiskReason: DisruptionReason? = nil
    var _affectedBy: String? = nil
    var _platformIsSuppressed: Bool? = nil
    var _platformIsSuppressedByCis: Bool? = nil
    var _platformDataSource: Forecast.PlatformDataSource? = nil
    var _platformIsConfirmed: Bool? = nil
    var _serviceIsSuppressed: Bool = false
    var _serviceDetatchesFromFront: Bool = false

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _isReverseFormation = source._isReverseFormation
      _scheduleLateReason = source._scheduleLateReason
      _estimatedPublicArrivalTime = source._estimatedPublicArrivalTime
      _estimatedWorkingArrivalTime = source._estimatedWorkingArrivalTime
      _estimatedMinimumArrivalTime = source._estimatedMinimumArrivalTime
      _arrivalIsDelayed = source._arrivalIsDelayed
      _arrivalIsDelayedByUnknownAmount = source._arrivalIsDelayedByUnknownAmount
      _estimatedPassingTime = source._estimatedPassingTime
      _estimatedMinimumPassingTime = source._estimatedMinimumPassingTime
      _passingIsDelayed = source._passingIsDelayed
      _passingIsDelayedByUnknownAmount = source._passingIsDelayedByUnknownAmount
      _estimatedPublicDepartureTime = source._estimatedPublicDepartureTime
      _estimatedWorkingDepartureTime = source._estimatedWorkingDepartureTime
      _estimatedMinimumDepartureTime = source._estimatedMinimumDepartureTime
      _departureIsDelayed = source._departureIsDelayed
      _departureIsDelayedByUnknownAmount = source._departureIsDelayedByUnknownAmount
      _actualArrivalTime = source._actualArrivalTime
      _actualArrivalDataClass = source._actualArrivalDataClass
      _actualArrivalDataSource = source._actualArrivalDataSource
      _actualArrivalDataSourceSystem = source._actualArrivalDataSourceSystem
      _actualPassingTime = source._actualPassingTime
      _actualPassingDataClass = source._actualPassingDataClass
      _actualPassingDataSource = source._actualPassingDataSource
      _actualPassingDataSourceSystem = source._actualPassingDataSourceSystem
      _actualDepartureTime = source._actualDepartureTime
      _actualDepartureDataClass = source._actualDepartureDataClass
      _actualDepartureDataSource = source._actualDepartureDataSource
      _actualDepartureDataSourceSystem = source._actualDepartureDataSourceSystem
      _locationLateReason = source._locationLateReason
      _locationDisruptionRisk = source._locationDisruptionRisk
      _locationDisruptionRiskReason = source._locationDisruptionRiskReason
      _affectedBy = source._affectedBy
      _platformIsSuppressed = source._platformIsSuppressed
      _platformIsSuppressedByCis = source._platformIsSuppressedByCis
      _platformDataSource = source._platformDataSource
      _platformIsConfirmed = source._platformIsConfirmed
      _serviceIsSuppressed = source._serviceIsSuppressed
      _serviceDetatchesFromFront = source._serviceDetatchesFromFront
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularBoolField(value: &_storage._isReverseFormation) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._scheduleLateReason) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._estimatedPublicArrivalTime) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._estimatedWorkingArrivalTime) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._estimatedMinimumArrivalTime) }()
        case 6: try { try decoder.decodeSingularBoolField(value: &_storage._arrivalIsDelayed) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._arrivalIsDelayedByUnknownAmount) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._estimatedPassingTime) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._estimatedMinimumPassingTime) }()
        case 10: try { try decoder.decodeSingularBoolField(value: &_storage._passingIsDelayed) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._passingIsDelayedByUnknownAmount) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._estimatedPublicDepartureTime) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._estimatedWorkingDepartureTime) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._estimatedMinimumDepartureTime) }()
        case 15: try { try decoder.decodeSingularBoolField(value: &_storage._departureIsDelayed) }()
        case 16: try { try decoder.decodeSingularBoolField(value: &_storage._departureIsDelayedByUnknownAmount) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._actualArrivalTime) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._actualArrivalDataClass) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._actualArrivalDataSource) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._actualArrivalDataSourceSystem) }()
        case 21: try { try decoder.decodeSingularStringField(value: &_storage._actualPassingTime) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._actualPassingDataClass) }()
        case 23: try { try decoder.decodeSingularStringField(value: &_storage._actualPassingDataSource) }()
        case 24: try { try decoder.decodeSingularStringField(value: &_storage._actualPassingDataSourceSystem) }()
        case 25: try { try decoder.decodeSingularStringField(value: &_storage._actualDepartureTime) }()
        case 26: try { try decoder.decodeSingularStringField(value: &_storage._actualDepartureDataClass) }()
        case 27: try { try decoder.decodeSingularStringField(value: &_storage._actualDepartureDataSource) }()
        case 28: try { try decoder.decodeSingularStringField(value: &_storage._actualDepartureDataSourceSystem) }()
        case 29: try { try decoder.decodeSingularMessageField(value: &_storage._locationLateReason) }()
        case 30: try { try decoder.decodeSingularStringField(value: &_storage._locationDisruptionRisk) }()
        case 31: try { try decoder.decodeSingularMessageField(value: &_storage._locationDisruptionRiskReason) }()
        case 32: try { try decoder.decodeSingularStringField(value: &_storage._affectedBy) }()
        case 33: try { try decoder.decodeSingularBoolField(value: &_storage._platformIsSuppressed) }()
        case 34: try { try decoder.decodeSingularBoolField(value: &_storage._platformIsSuppressedByCis) }()
        case 35: try { try decoder.decodeSingularEnumField(value: &_storage._platformDataSource) }()
        case 36: try { try decoder.decodeSingularBoolField(value: &_storage._platformIsConfirmed) }()
        case 37: try { try decoder.decodeSingularBoolField(value: &_storage._serviceIsSuppressed) }()
        case 38: try { try decoder.decodeSingularBoolField(value: &_storage._serviceDetatchesFromFront) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._isReverseFormation != false {
        try visitor.visitSingularBoolField(value: _storage._isReverseFormation, fieldNumber: 1)
      }
      try { if let v = _storage._scheduleLateReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._estimatedPublicArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._estimatedWorkingArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._estimatedMinimumArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._arrivalIsDelayed {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._arrivalIsDelayedByUnknownAmount {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._estimatedPassingTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._estimatedMinimumPassingTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._passingIsDelayed {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._passingIsDelayedByUnknownAmount {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._estimatedPublicDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._estimatedWorkingDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._estimatedMinimumDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._departureIsDelayed {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._departureIsDelayedByUnknownAmount {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._actualArrivalTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 17)
      } }()
      try { if let v = _storage._actualArrivalDataClass {
        try visitor.visitSingularStringField(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._actualArrivalDataSource {
        try visitor.visitSingularStringField(value: v, fieldNumber: 19)
      } }()
      try { if let v = _storage._actualArrivalDataSourceSystem {
        try visitor.visitSingularStringField(value: v, fieldNumber: 20)
      } }()
      try { if let v = _storage._actualPassingTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 21)
      } }()
      try { if let v = _storage._actualPassingDataClass {
        try visitor.visitSingularStringField(value: v, fieldNumber: 22)
      } }()
      try { if let v = _storage._actualPassingDataSource {
        try visitor.visitSingularStringField(value: v, fieldNumber: 23)
      } }()
      try { if let v = _storage._actualPassingDataSourceSystem {
        try visitor.visitSingularStringField(value: v, fieldNumber: 24)
      } }()
      try { if let v = _storage._actualDepartureTime {
        try visitor.visitSingularStringField(value: v, fieldNumber: 25)
      } }()
      try { if let v = _storage._actualDepartureDataClass {
        try visitor.visitSingularStringField(value: v, fieldNumber: 26)
      } }()
      try { if let v = _storage._actualDepartureDataSource {
        try visitor.visitSingularStringField(value: v, fieldNumber: 27)
      } }()
      try { if let v = _storage._actualDepartureDataSourceSystem {
        try visitor.visitSingularStringField(value: v, fieldNumber: 28)
      } }()
      try { if let v = _storage._locationLateReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 29)
      } }()
      try { if let v = _storage._locationDisruptionRisk {
        try visitor.visitSingularStringField(value: v, fieldNumber: 30)
      } }()
      try { if let v = _storage._locationDisruptionRiskReason {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 31)
      } }()
      try { if let v = _storage._affectedBy {
        try visitor.visitSingularStringField(value: v, fieldNumber: 32)
      } }()
      try { if let v = _storage._platformIsSuppressed {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 33)
      } }()
      try { if let v = _storage._platformIsSuppressedByCis {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 34)
      } }()
      try { if let v = _storage._platformDataSource {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 35)
      } }()
      try { if let v = _storage._platformIsConfirmed {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 36)
      } }()
      if _storage._serviceIsSuppressed != false {
        try visitor.visitSingularBoolField(value: _storage._serviceIsSuppressed, fieldNumber: 37)
      }
      if _storage._serviceDetatchesFromFront != false {
        try visitor.visitSingularBoolField(value: _storage._serviceDetatchesFromFront, fieldNumber: 38)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Forecast, rhs: Forecast) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._isReverseFormation != rhs_storage._isReverseFormation {return false}
        if _storage._scheduleLateReason != rhs_storage._scheduleLateReason {return false}
        if _storage._estimatedPublicArrivalTime != rhs_storage._estimatedPublicArrivalTime {return false}
        if _storage._estimatedWorkingArrivalTime != rhs_storage._estimatedWorkingArrivalTime {return false}
        if _storage._estimatedMinimumArrivalTime != rhs_storage._estimatedMinimumArrivalTime {return false}
        if _storage._arrivalIsDelayed != rhs_storage._arrivalIsDelayed {return false}
        if _storage._arrivalIsDelayedByUnknownAmount != rhs_storage._arrivalIsDelayedByUnknownAmount {return false}
        if _storage._estimatedPassingTime != rhs_storage._estimatedPassingTime {return false}
        if _storage._estimatedMinimumPassingTime != rhs_storage._estimatedMinimumPassingTime {return false}
        if _storage._passingIsDelayed != rhs_storage._passingIsDelayed {return false}
        if _storage._passingIsDelayedByUnknownAmount != rhs_storage._passingIsDelayedByUnknownAmount {return false}
        if _storage._estimatedPublicDepartureTime != rhs_storage._estimatedPublicDepartureTime {return false}
        if _storage._estimatedWorkingDepartureTime != rhs_storage._estimatedWorkingDepartureTime {return false}
        if _storage._estimatedMinimumDepartureTime != rhs_storage._estimatedMinimumDepartureTime {return false}
        if _storage._departureIsDelayed != rhs_storage._departureIsDelayed {return false}
        if _storage._departureIsDelayedByUnknownAmount != rhs_storage._departureIsDelayedByUnknownAmount {return false}
        if _storage._actualArrivalTime != rhs_storage._actualArrivalTime {return false}
        if _storage._actualArrivalDataClass != rhs_storage._actualArrivalDataClass {return false}
        if _storage._actualArrivalDataSource != rhs_storage._actualArrivalDataSource {return false}
        if _storage._actualArrivalDataSourceSystem != rhs_storage._actualArrivalDataSourceSystem {return false}
        if _storage._actualPassingTime != rhs_storage._actualPassingTime {return false}
        if _storage._actualPassingDataClass != rhs_storage._actualPassingDataClass {return false}
        if _storage._actualPassingDataSource != rhs_storage._actualPassingDataSource {return false}
        if _storage._actualPassingDataSourceSystem != rhs_storage._actualPassingDataSourceSystem {return false}
        if _storage._actualDepartureTime != rhs_storage._actualDepartureTime {return false}
        if _storage._actualDepartureDataClass != rhs_storage._actualDepartureDataClass {return false}
        if _storage._actualDepartureDataSource != rhs_storage._actualDepartureDataSource {return false}
        if _storage._actualDepartureDataSourceSystem != rhs_storage._actualDepartureDataSourceSystem {return false}
        if _storage._locationLateReason != rhs_storage._locationLateReason {return false}
        if _storage._locationDisruptionRisk != rhs_storage._locationDisruptionRisk {return false}
        if _storage._locationDisruptionRiskReason != rhs_storage._locationDisruptionRiskReason {return false}
        if _storage._affectedBy != rhs_storage._affectedBy {return false}
        if _storage._platformIsSuppressed != rhs_storage._platformIsSuppressed {return false}
        if _storage._platformIsSuppressedByCis != rhs_storage._platformIsSuppressedByCis {return false}
        if _storage._platformDataSource != rhs_storage._platformDataSource {return false}
        if _storage._platformIsConfirmed != rhs_storage._platformIsConfirmed {return false}
        if _storage._serviceIsSuppressed != rhs_storage._serviceIsSuppressed {return false}
        if _storage._serviceDetatchesFromFront != rhs_storage._serviceDetatchesFromFront {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Forecast.PlatformDataSource: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0PLATFORM_DATA_SOURCE_PLATFORM_UNKNOWN\0\u{1}PLATFORM_DATA_SOURCE_PLATFORM_PLANNED\0\u{1}PLATFORM_DATA_SOURCE_PLATFORM_AUTOMATIC\0\u{1}PLATFORM_DATA_SOURCE_PLATFORM_MANUAL\0")
}
